// frontend/src/app/layout/cookie-banner/cookie-banner.component.ts
import { Component } from "@angular/core";
import { AnalyticsService } from "../../shared/services/analytics.service";
import { CookiePolicyService } from "../../shared/services/cookie-policy.service";

@Component({
  selector: "app-cookie-banner",
  templateUrl: "./cookie-banner.component.html",
  styleUrls: ["./cookie-banner.component.scss"],
})
export class CookieBannerComponent {
  hidden = false;
  submitted = false;

  get analyticsEnabled(): boolean {
    return this.cookiePolicyService.getAnalyticsPolicy().analyticsEnabled;
  }

  constructor(
    private analyticsService: AnalyticsService,
    private cookiePolicyService: CookiePolicyService,
  ) {
    this.hidden = this.cookiePolicyService.getCookiePolicySubmitted();
  }

  onAccept() {
    this.analyticsService.enableAnalytics(true);
    this.submitted = true;
  }

  onReject() {
    this.analyticsService.disableAnalytics(true);
    this.submitted = true;
  }

  onHide() {
    this.hidden = true;
  }
}

<div
  *ngIf="!hidden"
  class="govuk-cookie-banner"
  data-nosnippet
  role="region"
  aria-label="Cookies on Analyse Bus Open Data"
>
  <div app-inner class="govuk-cookie-banner__message">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <h2 class="govuk-cookie-banner__heading govuk-heading-m">
          Cookies on Analyse Bus Open Data
        </h2>
        <div class="govuk-cookie-banner__content">
          <ng-container *ngIf="!submitted">
            <p class="govuk-body">
              We use some essential cookies to make this service work.
            </p>
            <p class="govuk-body">
              We’d also like to use analytics cookies so we can understand how
              you use the service and make improvements.
            </p>
          </ng-container>
          <p *ngIf="submitted && analyticsEnabled" class="govuk-body">
            You’ve accepted analytics cookies. You can
            <a
              class="govuk-link"
              [attr.data-qa]="'view-cookies-accept'"
              routerLink="/cookies"
              >change your cookie settings</a
            >
            at any time.
          </p>
          <p *ngIf="submitted && !analyticsEnabled" class="govuk-body">
            You’ve rejected analytics cookies. You can
            <a
              class="govuk-link"
              [attr.data-qa]="'view-cookies-reject'"
              routerLink="/cookies"
              >change your cookie settings</a
            >
            at any time.
          </p>
        </div>
      </div>
    </div>
    <div class="govuk-button-group">
      <gds-button
        *ngIf="submitted"
        buttonId="hide-cookie-message"
        (click)="onHide()"
        >Hide cookie message</gds-button
      >
      <ng-container *ngIf="!submitted">
        <gds-button (click)="onAccept()" buttonId="accept-cookies"
          >Accept analytics cookies</gds-button
        >
        <gds-button (click)="onReject()" buttonId="reject-cookies"
          >Reject analytics cookies</gds-button
        >
        <a
          id="view-cookies"
          [attr.data-qa]="'view-cookies'"
          class="govuk-link button-link"
          routerLink="/cookies"
          >View cookies</a
        >
      </ng-container>
    </div>
  </div>
</div>

// frontend-two/components/layout/CookieBanner.tsx
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useConfig } from "@/contexts/ConfigContext";

interface CookiePolicy {
  analyticsEnabled: boolean;
  version: number;
  userSubmitted: boolean;
}

const COOKIE_KEY = "abod_cookies_policy";

const loadPolicy = (fallback: CookiePolicy): CookiePolicy => {
  if (typeof window === "undefined") return fallback;
  const raw = localStorage.getItem(COOKIE_KEY);
  if (!raw) return fallback;
  try {
    return JSON.parse(raw) as CookiePolicy;
  } catch {
    return fallback;
  }
};

const savePolicy = (policy: CookiePolicy) => {
  if (typeof window === "undefined") return;
  localStorage.setItem(COOKIE_KEY, JSON.stringify(policy));
};

export const CookieBanner = () => {
  const { config } = useConfig();
  const defaultPolicy = useMemo<CookiePolicy>(
    () =>
      config?.defaultCookiePolicy ?? {
        analyticsEnabled: false,
        version: 1,
        userSubmitted: false,
      },
    [config?.defaultCookiePolicy],
  );
  const [policy, setPolicy] = useState<CookiePolicy>(defaultPolicy);

  useEffect(() => {
    setPolicy(loadPolicy(defaultPolicy));
  }, [defaultPolicy]);

  const updatePolicy = (analyticsEnabled: boolean) => {
    const updated = { ...policy, analyticsEnabled, userSubmitted: true };
    setPolicy(updated);
    savePolicy(updated);
  };

  if (policy.userSubmitted) {
    return null;
  }

  return (
    <section
      className="govuk-cookie-banner"
      aria-label="Cookies on Analyse Bus Open Data"
    >
      <div className="govuk-cookie-banner__message govuk-width-container">
        <div className="govuk-grid-row">
          <div className="govuk-grid-column-two-thirds">
            <h2 className="govuk-cookie-banner__heading govuk-heading-m">
              Cookies on Analyse Bus Open Data
            </h2>
            <div className="govuk-cookie-banner__content">
              <p className="govuk-body">
                We use some essential cookies to make this service work. We’d
                also like to use analytics cookies so we can understand how you
                use the service and make improvements.
              </p>
            </div>
          </div>
        </div>
        <div className="govuk-button-group">
          <button
            className="govuk-button"
            type="button"
            onClick={() => updatePolicy(true)}
          >
            Accept analytics cookies
          </button>
          <button
            className="govuk-button govuk-button--secondary"
            type="button"
            onClick={() => updatePolicy(false)}
          >
            Reject analytics cookies
          </button>
          <Link className="govuk-link" href="/cookies/">
            View cookies
          </Link>
        </div>
      </div>
    </section>
  );
};
