// frontend-two/components/shared/PagingPanel/index.tsx
const MINIMUM_PAGES = 8;
const STICKY_THRESHOLD = 4;
const PAGES_STICKY = 5;
const PAGES_MIDDLE = 3;

function getPageNumbers(current: number, total: number) {
  const stickToStart = total <= MINIMUM_PAGES || current < STICKY_THRESHOLD;
  const stickToEnd = total <= MINIMUM_PAGES || total - current - 1 < STICKY_THRESHOLD;

  const offset = stickToStart
    ? 0
    : stickToEnd
      ? total - STICKY_THRESHOLD - 1
      : current - Math.floor(PAGES_MIDDLE / 2);

  const numPages =
    total <= MINIMUM_PAGES
      ? total
      : Math.min(total, stickToStart || stickToEnd ? PAGES_STICKY : PAGES_MIDDLE);

  const pages = Array(numPages)
    .fill(0)
    .map((_, i) => i + offset);

  return { pages, stickToStart, stickToEnd };
}

interface PagingPanelProps {
  currentPage: number;
  totalPages: number;
  pageSize: number;
  rowCount: number;
  noun?: string;
  onPageChange: (page: number) => void;
}

export const PagingPanel = ({
  currentPage,
  totalPages,
  pageSize,
  rowCount,
  noun = "row",
  onPageChange,
}: PagingPanelProps) => {
  if (totalPages === 0 || rowCount === 0) return null;

  const firstRow = pageSize * currentPage + 1;
  const lastRow = Math.min(firstRow + pageSize - 1, rowCount);
  const isFirstPage = currentPage === 0;
  const isLastPage = currentPage === totalPages - 1;
  const pluralNoun = `${noun}${rowCount > 1 ? "s" : ""}`;

  const { pages, stickToStart, stickToEnd } = getPageNumbers(currentPage, totalPages);

  return (
    <div className="paging-panel flex justify-end">
      <div className="w-full flex items-center justify-between">
        <span className="govuk-body paging-panel__count">
          Showing {firstRow} - {lastRow} of {rowCount} {pluralNoun}
        </span>
        <div className="govuk-body paging-panel__controls">
          {totalPages > 1 && (
            <div className="flex items-center gap-2">
              {!isFirstPage && (
                <button
                  className="button-link paging-panel__prev"
                  aria-label="Previous page"
                  onClick={() => onPageChange(currentPage - 1)}
                >
                  « Prev
                </button>
              )}
              {!stickToStart && (
                <>
                  <button className="button-link paging-panel__button" onClick={() => onPageChange(0)}>
                    1
                  </button>
                  <span className="paging-panel__ellipsis">…</span>
                </>
              )}
              {pages.map((page) =>
                page === currentPage ? (
                  <span key={page} className="paging-panel__current">
                    {page + 1}
                  </span>
                ) : (
                  <button key={page} className="button-link paging-panel__button" onClick={() => onPageChange(page)}>
                    {page + 1}
                  </button>
                ),
              )}
              {!stickToEnd && (
                <>
                  <span className="paging-panel__ellipsis">…</span>
                  <button
                    className="button-link paging-panel__button"
                    onClick={() => onPageChange(totalPages - 1)}
                  >
                    {totalPages}
                  </button>
                </>
              )}
              {!isLastPage && (
                <button
                  className="button-link paging-panel__next"
                  aria-label="Next page"
                  onClick={() => onPageChange(currentPage + 1)}
                >
                  Next »
                </button>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// frontend/src/app/shared/components/paging-panel/paging-panel.component.ts
import { Component, Input } from "@angular/core";
import { GridApi, PaginationChangedEvent } from "ag-grid-community";

const MINIMUM_PAGES = 8;
const STICKY_THRESHOLD = 4;
const PAGES_STICKY = 5;
const PAGES_MIDDLE = 3;

@Component({
  selector: "app-paging-panel",
  templateUrl: "paging-panel.component.html",
  styleUrls: ["./paging-panel.component.scss"],
})
export class PagingPanelComponent {
  @Input() noun = "row";
  firstRow?: number;
  lastRow?: number;
  current?: number;
  total?: number;
  rowCount?: number;
  isFirstPage?: boolean;
  isLastPage?: boolean;
  stickToStart?: boolean;
  stickToEnd?: boolean;
  pages?: number[];

  private gridApi?: GridApi;

  paginationChanged({ api }: PaginationChangedEvent) {
    this.gridApi = api;
    const pageSize = api.paginationGetPageSize() ?? 0;
    this.current = api.paginationGetCurrentPage() ?? 0;
    this.total = api.paginationGetTotalPages() ?? 0;
    this.rowCount = api.paginationGetRowCount() ?? 0;

    this.firstRow = this.total === 0 ? 0 : pageSize * this.current + 1;
    this.lastRow =
      this.total === 0
        ? 0
        : Math.min(this.firstRow + pageSize - 1, this.rowCount);

    this.isFirstPage = this.current === 0;
    this.isLastPage = this.current === this.total - 1;

    this.stickToStart =
      this.total <= MINIMUM_PAGES || this.current < STICKY_THRESHOLD;
    this.stickToEnd =
      this.total <= MINIMUM_PAGES ||
      this.total - this.current - 1 < STICKY_THRESHOLD;

    const offset = this.stickToStart
      ? 0
      : this.stickToEnd
        ? this.total - STICKY_THRESHOLD - 1
        : this.current - Math.floor(PAGES_MIDDLE / 2);
    const numPages =
      this.total <= MINIMUM_PAGES
        ? this.total
        : Math.min(
            this.total,
            this.stickToStart || this.stickToEnd ? PAGES_STICKY : PAGES_MIDDLE,
          );

    this.pages = Array(numPages)
      .fill(0)
      .map((_, i) => i + offset);
  }

  firstPage() {
    this.gridApi?.paginationGoToFirstPage();
  }

  previousPage() {
    this.gridApi?.paginationGoToPreviousPage();
  }

  goToPage(page: number) {
    this.gridApi?.paginationGoToPage(page);
  }

  nextPage() {
    this.gridApi?.paginationGoToNextPage();
  }

  lastPage() {
    this.gridApi?.paginationGoToLastPage();
  }

  get pluralNoun(): string {
    return `${this.noun}${this.total && this.total > 1 ? "s" : ""}`; // Good enough for now as we don't have any irregular plurals
  }
}

<div class="paging-panel" *ngIf="total && rowCount">
  <span class="paging-panel__count"
    >Showing {{ firstRow }} - {{ lastRow }} of {{ rowCount }}
    {{ pluralNoun }}</span
  >
  <div *ngIf="total > 1" class="paging-panel__controls">
    <button
      class="button-link paging-panel__prev"
      aria-label="Previous page"
      (click)="previousPage()"
      *ngIf="!isFirstPage"
    >
      Prev
    </button>
    <ng-container *ngIf="!stickToStart">
      <button class="button-link paging-panel__button" (click)="firstPage()">
        1
      </button>
      <span class="paging-panel__ellipsis"></span>
    </ng-container>
    <ng-template ngFor [ngForOf]="pages" let-page>
      <span
        *ngIf="current === page; else pageBtn"
        class="paging-panel__current"
        >{{ page + 1 }}</span
      >
      <ng-template #pageBtn>
        <button
          class="button-link paging-panel__button"
          (click)="goToPage(page)"
        >
          {{ page + 1 }}
        </button>
      </ng-template>
    </ng-template>
    <ng-container *ngIf="!stickToEnd">
      <span class="paging-panel__ellipsis"></span>
      <button class="button-link paging-panel__button" (click)="lastPage()">
        {{ total }}
      </button>
    </ng-container>
    <button
      class="button-link paging-panel__next"
      aria-label="Next page"
      (click)="nextPage()"
      *ngIf="!isLastPage"
    >
      Next
    </button>
  </div>
</div>
