// frontend-two/components/feed-monitoring/HistoricVehicleStats.tsx
import { useEffect, useRef } from "react";
import { DateTime } from "luxon";
import { VehicleStatFragment } from "../../src/generated/graphql";

import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_frozen from "@amcharts/amcharts4/themes/frozen";

import { COLOURS } from "@/utils/chart-colours";

interface ChartDataPoint {
  dateTime: DateTime;
  timestamp: Date;
  actual: number;
  expected: number;
  expectedFill?: any;
}

function buildChartData(stats: VehicleStatFragment[]): ChartDataPoint[] {
  if (!stats.length) return [];

  const protoData = stats.map((s) => {
    const dateTime = DateTime.fromISO(s.timestamp, { zone: "utc" });
    return {
      dateTime,
      timestamp: dateTime.toJSDate(),
      actual: s.actual ?? 0,
      expected: s.expected ?? 0,
    };
  });

  const minDateTime = protoData[0].dateTime;
  const maxDateTime = protoData[protoData.length - 1].dateTime.plus({
    minutes: 1,
  });

  const filled: ChartDataPoint[] = [];
  let i = 0;

  for (let ts = minDateTime; ts < maxDateTime; ts = ts.plus({ minute: 1 })) {
    const candidate = protoData[i];
    if (!candidate?.dateTime.equals(ts)) {
      filled.push({
        dateTime: ts,
        timestamp: ts.toJSDate(),
        actual: 0,
        expected: 0,
      });
    } else {
      filled.push(candidate);
      i += 1;
    }
  }

  return filled;
}

interface HistoricVehicleStatsProps {
  data: VehicleStatFragment[];
  date: DateTime;
}

const HistoricVehicleStats = ({ data, date }: HistoricVehicleStatsProps) => {
  const idRef = useRef(`historic-vehicle-stats`);
  const chartInstance = useRef<any>(null);

  useEffect(() => {
    am4core.useTheme(am4themes_frozen);

    const chart = am4core.create(idRef.current, am4charts.XYChart);
    chartInstance.current = chart;

    chart.paddingRight = 20;
    chart.paddingLeft = 0;
    chart.defaultState.transitionDuration = 0;

    // Date axis (X)
    const dateAxis = chart.xAxes.push(new am4charts.DateAxis());
    dateAxis.renderer.labels.template.fontSize = 13;
    dateAxis.renderer.labels.template.fill = am4core.color(
      COLOURS.legendaryGrey,
    );

    dateAxis.baseInterval = { timeUnit: "second", count: 1 };
    dateAxis.groupData = true;
    dateAxis.renderer.grid.template.disabled = true;
    dateAxis.renderer.cellStartLocation = 0;
    dateAxis.renderer.cellEndLocation = 1;
    if (dateAxis.tooltip) dateAxis.tooltip.disabled = true;

    // Value axis (Y)
    const valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis.renderer.labels.template.fontSize = 13;
    valueAxis.renderer.labels.template.fill = am4core.color(
      COLOURS.legendaryGrey,
    );
    valueAxis.min = 0;
    if (valueAxis.tooltip) valueAxis.tooltip.disabled = true;

    // Expected vehicles (continuous line with per-point fill/pattern)
    const expectedSeries = chart.series.push(new am4charts.LineSeries());
    expectedSeries.name = "Expected vehicles";
    expectedSeries.dataFields.dateX = "timestamp";
    expectedSeries.dataFields.valueY = "expected";
    expectedSeries.yAxis = valueAxis;
    expectedSeries.stroke = am4core.color(COLOURS.darkBlue);
    expectedSeries.strokeWidth = 2;
    expectedSeries.fillOpacity = 1;
    expectedSeries.tensionX = 0.8;
    expectedSeries.rangeChangeEasing = am4core.ease.linear;
    expectedSeries.groupFields.valueY = "open";
    expectedSeries.defaultState.transitionDuration = 100;
    expectedSeries.propertyFields.fill = "expectedFill";

    // Actual vehicle journeys
    const actualSeries = chart.series.push(new am4charts.LineSeries());
    actualSeries.name = "Vehicle journeys";
    actualSeries.dataFields.dateX = "timestamp";
    actualSeries.dataFields.valueY = "actual";
    actualSeries.dataFields.customValue = "expected";
    actualSeries.yAxis = valueAxis;
    actualSeries.stroke = am4core.color(COLOURS.lightBlue);
    actualSeries.fill = am4core.color(COLOURS.lightBlue);
    actualSeries.strokeWidth = 2;
    actualSeries.fillOpacity = 0.8;
    actualSeries.tensionX = 0.8;
    actualSeries.rangeChangeEasing = am4core.ease.linear;
    actualSeries.groupFields.valueY = "open";
    actualSeries.groupFields.customValue = "open";
    actualSeries.defaultState.transitionDuration = 100;

    actualSeries.tooltipHTML = `
      <div style="margin-bottom:5px"><b>{dateX.open.formatDate('HH:mm')}</b></div>
      <div style="margin-bottom:5px;display:flex">
        <span style="flex-grow:1">Vehicle journeys</span>
        <span style="margin-left:5px"><b>{valueY.open}</b></span>
      </div>
      <div style="margin-bottom:5px;display:flex">
        <span style="flex-grow:1">Expected vehicle journeys</span>
        <span style="float:right;margin-left:5px"><b>{customValue.open}</b></span>
      </div>`;

    if (actualSeries.tooltip) {
      actualSeries.tooltip.pointerOrientation = "vertical";
      actualSeries.tooltip.getFillFromObject = false;
      actualSeries.tooltip.stroke = am4core.color(COLOURS.black);
      actualSeries.tooltip.label.fill = am4core.color(COLOURS.black);
      actualSeries.tooltip.label.padding(10, 10, 5, 10);
      actualSeries.tooltip.background.cornerRadius = 0;
      actualSeries.tooltip.background.fillOpacity = 1;
      actualSeries.tooltip.background.filters.clear();
      actualSeries.tooltip.background.fill = am4core.color("#fff");
      actualSeries.tooltip.background.stroke = am4core.color(COLOURS.black);
    }

    // Cursor
    chart.cursor = new am4charts.XYCursor();
    chart.cursor.behavior = "zoomX";
    chart.cursor.lineY.disabled = true;
    chart.cursor.lineX.stroke = am4core.color(COLOURS.black);
    chart.cursor.lineX.strokeWidth = 2;
    chart.cursor.lineX.strokeOpacity = 1;
    chart.cursor.zIndex = 3;

    chart.maskBullets = false;

    // Data
    // Data: set expectedFill per point (pattern for outage, color for normal)
    const chartData = buildChartData(data);
    chartData.forEach((point) => {
      if (point.actual === 0 && point.expected > 0) {
        const pattern = new am4core.LinePattern();
        pattern.strokeWidth = 1;
        pattern.rotation = 135;
        pattern.stroke = am4core.color(COLOURS.blue);
        pattern.fill = am4core.color(COLOURS.blue);
        point.expectedFill = pattern;
      } else {
        point.expectedFill = am4core.color(COLOURS.darkBlue);
      }
    });
    chart.data = chartData;

    return () => {
      chart.dispose();
      chartInstance.current = null;
    };
  }, [data, date]);

  return (
    <div>
      <p className="govuk-caption-m" style={{ marginBottom: "8px" }}>
        Vehicle journeys
      </p>
      <div id={idRef.current} style={{ width: "100%", height: "300px" }} />
    </div>
  );
};

export default HistoricVehicleStats;

// frontend/src/app/feed-monitoring/feed-history/historic-vehicle-stats/historic-vehicle-stats.component.ts
import {
  AfterViewInit,
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
} from "@angular/core";
import {
  AlertTypeEnum,
  Granularity,
  VehicleStatsType,
} from "src/generated/graphql";
import { ChartService } from "src/app/shared/components/amcharts/chart.service";

import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_frozen from "@amcharts/amcharts4/themes/frozen";
import { DateTime, Interval } from "luxon";
import { VehicleStatsViewModel } from "../../types";
import { BaseChart } from "src/app/shared/components/amcharts/base-chart";

@Component({
  selector: "app-historic-vehicle-stats",
  templateUrl: "./historic-vehicle-stats.component.html",
  styleUrls: ["./historic-vehicle-stats.component.scss"],
})
export class HistoricVehicleStatsComponent
  extends BaseChart
  implements OnChanges, AfterViewInit, OnDestroy
{
  @Input() chartId?: string;
  @Input() dataSource?: VehicleStatsType[];
  @Input() date?: DateTime;

  @Input() alertsDataSource?: {
    timestamp: DateTime;
    type: AlertTypeEnum;
    id: string;
  }[];

  @Output() alertSelected = new EventEmitter<string>();

  timelineSeries?: am4charts.XYSeries;

  chartInterval?: Interval;

  constructor(protected chartService: ChartService) {
    super(am4themes_frozen, chartService);
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.dataSource && changes.dataSource.currentValue?.length) {
      this.setData(changes.dataSource.currentValue);
      if (this.alertsDataSource) {
        this.setTimelineData(this.alertsDataSource);
      }
    }
    if (
      changes.alertsDataSource &&
      changes.alertsDataSource.currentValue &&
      this.timelineSeries
    ) {
      this.setTimelineData(changes.alertsDataSource.currentValue);
    }
  }

  private setData(withData: VehicleStatsType[]) {
    if (!this.chart) {
      return;
    }

    const protoViewData = withData.map((stat) => {
      const dateTime = DateTime.fromISO(stat.timestamp, { zone: "utc" });
      return {
        dateTime,
        timestamp: dateTime.toJSDate(),
        actual: stat.actual ?? 0,
        expected: stat.expected ?? 0,
      };
    });

    const minDateTime = protoViewData[0].dateTime;
    const maxDateTime = protoViewData[protoViewData.length - 1].dateTime.plus({
      minutes: 1,
    });

    this.chartInterval = Interval.fromDateTimes(minDateTime, maxDateTime);

    const viewData: VehicleStatsViewModel[] = [];

    let i = 0;

    const outagePattern = this.createPattern();
    const expectedFill = this.chart.colors.getIndex(2);

    for (
      let ts = minDateTime;
      this.chartInterval.contains(ts);
      ts = ts.plus({ minute: 1 })
    ) {
      const candidateStat = protoViewData[i];
      if (!candidateStat || !candidateStat.dateTime.equals(ts)) {
        viewData.push({
          dateTime: ts,
          timestamp: ts.toJSDate(),
          actual: 0,
          expected: 0,
        });
      } else {
        viewData.push({
          ...candidateStat,
          expectedFill:
            candidateStat.actual === 0 ? outagePattern : expectedFill,
        });
        i += 1;
      }
    }

    this.chart.data = viewData;
    this.screens.loadingScreen?.hide();
  }

  get bulletFills(): { [k in AlertTypeEnum]: am4core.Color } {
    return {
      [AlertTypeEnum.FeedAvailableEvent]: this.chartService.colorMap.green,
      [AlertTypeEnum.FeedUnavailableEvent]: this.chartService.colorMap.red,
      [AlertTypeEnum.VehicleCountDisparityEvent]:
        this.chartService.colorMap.orange,
      [AlertTypeEnum.VehicleCountDisparity]: this.chartService.colorMap.orange,
      [AlertTypeEnum.FeedFailure]: this.chartService.colorMap.red,
      [AlertTypeEnum.FeedComplianceFailure]: this.chartService.colorMap.orange,
    };
  }

  setTimelineData(
    data: { timestamp: DateTime; type: AlertTypeEnum; id: string }[],
  ) {
    if (!this.timelineSeries) {
      return;
    }

    this.timelineSeries.data = data
      // only plot events that are in the same time period as the main graph
      .filter(
        ({ timestamp }) => this.chartInterval?.contains(timestamp) ?? true,
      )
      .map(({ timestamp, type, id }) => ({
        timestamp: timestamp.toJSDate(),
        value: 0,
        fill: this.bulletFills[type],
        id,
      }));
  }

  ngAfterViewInit() {
    this.chartService.browserOnly(() => this.renderChart());
  }

  createDateAxis() {
    if (!this.chart) {
      return;
    }

    const dateAxis = this.chart.xAxes.push(new am4charts.DateAxis());
    dateAxis.renderer.labels.template.fontSize = 13;
    dateAxis.renderer.labels.template.fill =
      this.chartService.colorMap.legendaryGrey;
    dateAxis.baseInterval = {
      timeUnit: "second",
      count: 1,
    };

    dateAxis.renderer.grid.template.disabled = true;
    dateAxis.renderer.cellStartLocation = 0;
    dateAxis.renderer.cellEndLocation = 1;

    dateAxis.groupData = true;

    if (dateAxis.tooltip) {
      dateAxis.tooltip.disabled = true;
    }
  }

  createValueAxis() {
    const valueAxis = new am4charts.ValueAxis();

    if (this.chart) {
      this.chart.yAxes.push(valueAxis);
      valueAxis.renderer.labels.template.fontSize = 13;
      valueAxis.renderer.labels.template.fill = this.chart.colors.getIndex(6);

      valueAxis.min = 0;

      if (valueAxis.tooltip) {
        valueAxis.tooltip.disabled = true;
      }
    }

    return valueAxis;
  }

  createTimelineAxis() {
    const timelineAxis = new am4charts.ValueAxis();

    if (this.chart) {
      this.chart.yAxes.push(timelineAxis);
    }

    timelineAxis.min = -0.1;
    timelineAxis.max = 0.1;

    timelineAxis.height = 30;
    timelineAxis.renderer.grid.template.strokeWidth = 3;
    timelineAxis.renderer.grid.template.strokeLinecap = "round";

    if (timelineAxis.tooltip) {
      timelineAxis.tooltip.disabled = true;
    }

    timelineAxis.renderer.labels.template.disabled = true;

    timelineAxis.renderer.baseGrid.disabled = true;

    timelineAxis.marginTop = 12;

    return timelineAxis;
  }

  createActualSeries(axis: am4charts.Axis) {
    if (!this.chart) {
      return;
    }
    const series = this.chart.series.push(new am4charts.LineSeries());
    series.name = "Vehicle journeys";
    series.dataFields.dateX = "timestamp";
    series.dataFields.valueY = "actual";
    series.dataFields.customValue = "expected";
    series.rangeChangeEasing = am4core.ease.linear;
    series.groupFields.valueY = "open";
    series.groupFields.customValue = "open";

    series.yAxis = axis;

    series.tooltipHTML = `
      <div style="margin-bottom: 5px;"><b>{dateX.open.formatDate('HH:mm')}</b></div>
      <div style="margin-bottom: 5px; display:flex">
        <span style="flex-grow:1">Vehicle journeys</span><span style="margin-left:5px;"><b>{valueY.open}</b></span>
      </div>
      <div style="margin-bottom: 5px; display: flex;">
        <span style="flex-grow:1">Expected vehicle journeys</span>
        <span style="float:right; margin-left:5px;"><b>{customValue.open}</b></span>
      </div>`;
    if (series.tooltip) {
      series.tooltip.pointerOrientation = "vertical";
      series.tooltip.getFillFromObject = false;
      series.tooltip.label.fill = this.chart.colors.getIndex(5);
      series.tooltip.label.padding(10, 10, 5, 10);
      series.tooltip.background.cornerRadius = 0;
      series.tooltip.background.filters.clear();
      series.tooltip.background.fillOpacity = 1;
      series.tooltip.background.fill = am4core.color("#fff");
      series.tooltip.background.stroke = this.chart.colors.getIndex(5);
    }
    series.stroke = this.chart.colors.getIndex(0);
    series.fill = this.chart.colors.getIndex(0);

    series.fillOpacity = 0.8;

    series.tensionX = 0.8;

    return series;
  }

  createExpectedSeries(axis: am4charts.Axis) {
    if (!this.chart) {
      return;
    }
    const series = this.chart.series.push(new am4charts.LineSeries());
    series.name = "Expected vehicles";
    series.dataFields.dateX = "timestamp";
    series.dataFields.valueY = "expected";
    series.rangeChangeEasing = am4core.ease.linear;
    series.groupFields.valueY = "open";

    series.yAxis = axis;

    series.stroke = this.chart.colors.getIndex(2);
    series.fill = this.chart.colors.getIndex(2);

    series.propertyFields.fill = "expectedFill";

    series.fillOpacity = 1;

    series.tensionX = 0.8;

    return series;
  }

  createTimeLineSeries(axis: am4charts.Axis) {
    if (!this.chart) {
      return;
    }
    const series = this.chart.series.push(new am4charts.XYSeries());

    series.dataFields.dateX = "timestamp";
    series.dataFields.valueY = "value";

    series.yAxis = axis;

    const bullet = series.bullets.push(new am4charts.Bullet());

    bullet.clickable = true;
    bullet.propertyFields.id = "id";
    bullet.events.on("hit", (ev) => this.alertSelected.emit(ev.target.id));
    bullet.cursorOverStyle = am4core.MouseCursorStyle.pointer;
    bullet.setStateOnChildren = true;

    bullet.zIndex = 10;

    const circle = bullet.createChild(am4core.Circle);
    circle.width = 12;
    circle.height = 12;

    const hover = circle.states.create("hover");
    hover.properties.width = 16;
    hover.properties.height = 16;

    circle.stroke = this.chartService.colorMap.lightGrey;
    circle.strokeWidth = 2;
    circle.propertyFields.fill = "fill";

    return series;
  }

  createChart() {
    this.chart = am4core.create(this.chartId, am4charts.XYChart);
    this.chart.colors.list = this.chartService.chartColorList;
    this.chart.fontFamily = this.chartService.getFontFamily();
    this.chart.paddingRight = 20;
    this.chart.paddingLeft = 0;

    this.chart.leftAxesContainer.layout = "vertical";

    this.createDateAxis();
    const valueAxis = this.createValueAxis();
    const timeLineAxis = this.createTimelineAxis();
    this.createExpectedSeries(valueAxis);
    this.createActualSeries(valueAxis);

    this.timelineSeries = this.createTimeLineSeries(timeLineAxis);

    if (this.dataSource?.length) {
      this.setData(this.dataSource);
    }

    if (this.alertsDataSource) {
      this.setTimelineData(this.alertsDataSource);
    }

    this.chart.cursor = new am4charts.XYCursor();
    this.chart.cursor.behavior = "zoomX";
    this.chart.cursor.lineY.disabled = true;
    this.chart.cursor.lineX.stroke = this.chartService.colorMap.black;
    this.chart.cursor.lineX.strokeWidth = 2;
    this.chart.cursor.lineX.strokeOpacity = 1;

    this.chart.cursor.zIndex = 3;

    this.chart.maskBullets = false;
  }

  createPattern() {
    if (!this.chart) {
      return;
    }

    const pattern = new am4core.LinePattern();
    pattern.strokeWidth = 1;
    pattern.rotation = 135;
    pattern.stroke = this.chart.colors.getIndex(1);
    pattern.fill = this.chart.colors.getIndex(1);
    return pattern;
  }

  ngOnDestroy() {
    this.chartService.browserOnly(() => {
      if (this.chart) {
        this.chart.dispose();
      }
    });
  }
}

<app-box>
  <div class="historic-vehicle-stats__label govuk-caption-m">
    Vehicle journeys
  </div>
  <div class="historic-vehicle-stats__graph" [id]="chartId"></div>
</app-box>
