// frontend-two/components/dashboard/FeedStatusSummary.tsx
import { Box } from "@/components/shared/Box";
import { Status } from "@/components/shared/Status";
import { Tooltip } from "@/components/shared/Tooltip";
import { LinkWithArrow } from "@/components/shared/LinkWithArrow";
import { DashboardOperatorListQuery } from "../../src/generated/graphql";

interface FeedStatusSummaryProps {
  operators: DashboardOperatorListQuery["operatorsFeedMonitoring"];
}

export const FeedStatusSummary = ({ operators }: FeedStatusSummaryProps) => (
  <Box className="app-feed-status-summary">
    <h2 className="govuk-heading-m">Feed status</h2>
    <table className="feed-status-summary">
      <thead>
        <tr>
          <th className="feed-status-summary__heading">
            <span className="govuk-visually-hidden">Status</span>
          </th>
          <th className="feed-status-summary__heading">
            <span className="govuk-visually-hidden">Operators</span>
          </th>
        </tr>
      </thead>
      <tbody>
        {operators.length === 0 ? (
          <tr>
            <td
              className="feed-status-summary__operator feed-status-summary__operator--muted"
              colSpan={2}
            >
              No operators available.
            </td>
          </tr>
        ) : (
          operators.map((operator) => (
            <tr key={operator.operatorId}>
              <td className="feed-status-summary__status">
                <Status
                  active={Boolean(operator.feedMonitoring?.feedStatus)}
                  size="small"
                  label={false}
                />
              </td>
              <td className="feed-status-summary__operator">
                <Tooltip message={operator.operatorId} selectable>
                  <span>{operator.name}</span>
                </Tooltip>
              </td>
            </tr>
          ))
        )}
      </tbody>
    </table>
    <div className="feed-status-summary__footer">
      <LinkWithArrow href="/feed-monitoring">NOC feed monitoring</LinkWithArrow>
    </div>
  </Box>
);

// frontend/src/app/dashboard/feed-status-summary/feed-status-summary.component.ts
import { Component, Input } from "@angular/core";
import { OperatorDashboardFragment } from "src/generated/graphql";

@Component({
  selector: "app-feed-status-summary",
  templateUrl: "./feed-status-summary.component.html",
  styleUrls: ["./feed-status-summary.component.scss"],
})
export class FeedStatusSummaryComponent {
  @Input() operators: OperatorDashboardFragment[] = [];
}

<app-box>
  <h2 class="govuk-heading-m">Feed status</h2>
  <table class="feed-status-summary">
    <thead>
      <tr>
        <th class="feed-status-summary__heading">
          <span class="govuk-visually-hidden">Status</span>
        </th>
        <th class="feed-status-summary__heading">
          <span class="govuk-visually-hidden">Operators</span>
        </th>
        <!-- <th class="feed-status-summary__heading">Alerts</th>
        <th class="feed-status-summary__heading">Errors</th> -->
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let operator of operators">
        <td class="feed-status-summary__status">
          <app-status
            [active]="operator.feedMonitoring?.feedStatus ?? false"
            size="small"
            [label]="false"
          ></app-status>
        </td>
        <td class="feed-status-summary__operator">
          <app-tooltip [message]="operator.operatorId" [selectable]="true">{{
            operator.name
          }}</app-tooltip>
        </td>
        <!-- <td
          class="feed-status-summary__count feed-status-summary__count--alerts"
        >
          {{ operator.feedMonitoring?.liveStats?.feedAlerts || 0 }}
        </td>
        <td
          class="feed-status-summary__count feed-status-summary__count--errors"
        >
          {{ operator.feedMonitoring?.liveStats?.feedErrors || 0 }}
        </td> -->
      </tr>
    </tbody>
  </table>
  <div class="feed-status-summary__footer">
    <app-link
      [route]="['/feed-monitoring/']"
      weight="bold"
      [arrows]="true"
      [underline]="false"
      >NOC feed monitoring</app-link
    >
  </div>
</app-box>
