// frontend/components/layout/Nav/Nav.tsx
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "./nav.module.scss";
import { useAuth } from "@/hooks/useAuth";
import { useNav } from "@/contexts/NavContext";
import { UserAccount } from "@/components/layout/UserAccount";
import { useHelpdesk } from "@/contexts/HelpdeskContext";
import QuestionInCircleIcon from "@/assets/icons/question-in-circle.svg";
import { clsx } from "clsx";

interface NavItem {
  href: string;
  label: string;
  requiresServiceMonitoring?: boolean;
  requiresDistances?: boolean;
}

const normalizePath = (path: string) =>
  path.split("?")[0].replace(/\/+$/, "") || "/";

const isActiveNavItem = (currentPath: string, itemPath: string) =>
  currentPath === itemPath || currentPath.startsWith(`${itemPath}/`);

const navItems: NavItem[] = [
  { href: "/dashboard", label: "Dashboard" },
  { href: "/feed-monitoring", label: "NOC feed monitoring" },
  { href: "/on-time", label: "On-time performance" },
  { href: "/vehicle-journeys", label: "Vehicle journeys" },
  { href: "/corridors", label: "Corridors" },
  {
    href: "/service-monitoring",
    label: "Service monitoring",
    requiresServiceMonitoring: true,
  },
  { href: "/data-monitoring", label: "Data monitoring" },
  { href: "/stop-analysis", label: "Stop analysis" },
  { href: "/distances", label: "Distances", requiresDistances: true },
];

export const Nav = () => {
  const router = useRouter();
  const { user } = useAuth();
  const { open: openHelpdesk } = useHelpdesk();
  const { isOpen, close } = useNav();
  const currentPath = normalizePath(router.asPath);

  const filteredNavItems = navItems.filter((item) => {
    if (item.requiresServiceMonitoring && !user?.canViewServiceMonitoring) {
      return false;
    }
    if (item.requiresDistances && !user?.canViewDistances) {
      return false;
    }
    return true;
  });

  return (
    <nav
      id="navigation"
      className={clsx(styles.nav, isOpen && styles.open)}
      aria-label="Primary"
    >
      <div className={styles.block} id="nav">
        <ul className="govuk-list">
          {filteredNavItems.map((item) => {
            const isActive = isActiveNavItem(currentPath, item.href);
            return (
              <li key={item.href} className={styles.item}>
                <Link
                  href={item.href}
                  onClick={close}
                  className={clsx(styles.link, isActive && styles.linkCurrent)}
                >
                  {item.label}
                </Link>
              </li>
            );
          })}
        </ul>
      </div>

      <div className={styles.menuBottom}>
        <button
          className={clsx(styles.menuBottomActionItem, "button-link")}
          onClick={openHelpdesk}
          aria-label="Help"
        >
          <QuestionInCircleIcon aria-hidden width="20" height="20" />
          Help
        </button>
        <UserAccount />
      </div>
    </nav>
  );
};

// frontend/src/app/layout/nav/nav.component.ts
import { Component, OnInit } from "@angular/core";
import { initAll } from "govuk-frontend";
import { HelpdeskPanelService } from "../../shared/components/helpdesk-panel/helpdesk-panel.service";
import { NavService } from "./nav.service";
import { ConfigService } from "../../config/config.service";

@Component({
  selector: "app-nav",
  templateUrl: "./nav.component.html",
  styleUrls: ["./nav.component.scss"],
})
export class NavComponent implements OnInit {
  constructor(
    public navService: NavService,
    private helpdeskPanelService: HelpdeskPanelService,
    public configService: ConfigService,
  ) {}

  ngOnInit(): void {
    initAll();
  }

  openHelpdesk() {
    this.helpdeskPanelService.open();
  }
}

<div
  id="navigation"
  class="nav"
  [ngClass]="{ 'nav--open': navService.isOpen }"
  (appMouseupOutside)="navService.navClickOutside($event)"
>
  <div class="nav__block" id="nav">
    <nav>
      <ul class="govuk-list nav__list">
        <li class="nav__item">
          <a
            class="nav__link"
            [routerLink]="['/dashboard']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >Dashboard
          </a>
        </li>
        <li class="nav__item">
          <a
            class="nav__link"
            [routerLink]="['/feed-monitoring']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >NOC feed monitoring
          </a>
        </li>
        <li class="nav__item">
          <a
            class="nav__link"
            [routerLink]="['/on-time']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >On-time performance
          </a>
        </li>
        <li class="nav__item">
          <a
            class="nav__link"
            [routerLink]="['/vehicle-journeys']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >Vehicle journeys
          </a>
        </li>
        <li class="nav__item">
          <a
            class="nav__link"
            [routerLink]="['/corridors']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >Corridors
          </a>
        </li>
        <li *ngIf="canViewServiceMonitoring | async" class="nav__item">
          <a
            class="nav__link"
            [routerLink]="['/service-monitoring']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >Service monitoring
          </a>
        </li>
        <li class="nav__item" *ngIf="canViewDataMonitoring | async">
          <a
            class="nav__link"
            [routerLink]="['/data-monitoring']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >Data monitoring
          </a>
        </li>
        <li class="nav__item" *ngIf="canViewStopAnalysis | async">
          <a
            class="nav__link"
            [routerLink]="['/stop-analysis']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >Stop analysis
          </a>
        </li>
        <li class="nav__item">
          <a
            class="nav__link"
            [routerLink]="['/distances']"
            routerLinkActive="nav__link--current"
            (click)="navService.closeMenu()"
            >Distances
          </a>
        </li>
      </ul>
    </nav>
  </div>

  <div class="nav__menu-bottom">
    <button
      class="nav__menu-bottom__action-item button-link"
      (click)="openHelpdesk()"
    >
      <svg-icon src="assets/icons/question-in-circle.svg"></svg-icon>
      Help
    </button>
    <app-user-account></app-user-account>
  </div>
</div>
