// frontend/src/app/on-time/filter-chips/filter-chips.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
} from "@angular/core";
import { PerformanceFiltersInputType } from "../../../generated/graphql";
import { AdminArea, AdminAreaService } from "../admin-area/admin-area.service";
import { isNotNullOrUndefined } from "../../shared/rxjs-operators";
import { map } from "rxjs/operators";
import { entries as _entries } from "lodash-es";

export interface DayOfWeekLabel {
  monday: "Mon";
  tuesday: "Tue";
  wednesday: "Wed";
  thursday: "Thur";
  friday: "Fri";
  saturday: "Sat";
  sunday: "Sun";
}

@Component({
  selector: "app-filter-chips",
  templateUrl: "./filter-chips.component.html",
  styleUrls: ["./filter-chips.component.scss"],
})
export class FilterChipsComponent implements OnChanges {
  @Input() showAdminAreas = true;
  @Input() filters: PerformanceFiltersInputType = {};
  @Output() filterChange = new EventEmitter<PerformanceFiltersInputType>();

  get isDayOfWeek(): boolean {
    return !!this.filters.dayOfWeekFlags;
  }

  get isTimeRange(): boolean {
    return !!this.filters.startTime || !!this.filters.endTime;
  }

  get isMinDelay(): boolean {
    return !!this.filters.minDelay;
  }

  get isMaxDelay(): boolean {
    return !!this.filters.maxDelay;
  }

  dayOfWeekValueMap: DayOfWeekLabel = {
    monday: "Mon",
    tuesday: "Tue",
    wednesday: "Wed",
    thursday: "Thur",
    friday: "Fri",
    saturday: "Sat",
    sunday: "Sun",
  };

  private readonly weekends = "Sat, Sun";
  private readonly weekdays = "Mon, Tue, Wed, Thur, Fri";

  get dayOfWeekValues(): string {
    const value = _entries(this.filters.dayOfWeekFlags ?? {})
      .filter(([, value]) => value)
      .map(([day]) => this.dayOfWeekValueMap[day as keyof DayOfWeekLabel])
      .join(", ");

    if (value === this.weekdays) {
      return "Weekdays";
    }
    if (value === this.weekends) {
      return "Weekends";
    }

    return value;
  }

  get timeRange(): string {
    return this.filters.startTime + " - " + this.filters.endTime;
  }

  get minDelay(): string {
    if (this.filters.minDelay) {
      return this.filters.minDelay * -1 + " minutes";
    }
    return "";
  }

  get maxDelay(): string {
    return this.filters.maxDelay + " minutes";
  }

  adminAreas: AdminArea[] = [];

  constructor(private adminAreaService: AdminAreaService) {}

  ngOnChanges() {
    const nocCode = this.filters.nocCodes?.[0];
    const adminAreaIds =
      this.filters.adminAreaIds?.filter(isNotNullOrUndefined) ?? [];

    // This ought to happen synchronously, since admin area data should be cached and never change
    (nocCode
      ? this.adminAreaService.fetchAdminAreasForOperator(nocCode)
      : this.adminAreaService.fetchAdminAreas()
    )
      .pipe(
        map((adminAreas) =>
          adminAreas.filter((adminArea) => adminAreaIds.includes(adminArea.id)),
        ),
      )
      .subscribe((adminAreas) => (this.adminAreas = adminAreas));
  }

  onClearDayOfWeekFilter() {
    const { dayOfWeekFlags, ...filters } = this.filters;
    this.updateFilters(filters);
  }

  onClearTimeRangeFilter() {
    const { startTime, endTime, ...filters } = this.filters;
    this.updateFilters(filters);
  }

  onClearMinDelayFilter() {
    const { minDelay, ...filters } = this.filters;
    this.updateFilters(filters);
  }

  onClearMaxDelayFilter() {
    const { maxDelay, ...filters } = this.filters;
    this.updateFilters(filters);
  }

  clearAdminAreaFilter(adminAreaId: string) {
    this.updateFilters({
      ...this.filters,
      adminAreaIds: this.filters.adminAreaIds?.filter(
        (id) => id !== adminAreaId,
      ),
    });
  }

  updateFilters(filters: PerformanceFiltersInputType) {
    this.filters = filters;
    this.filterChange.emit(filters);
  }
}

<ul
  *ngIf="
    adminAreas.length || isDayOfWeek || isTimeRange || isMinDelay || isMaxDelay
  "
  class="filter-chips"
>
  <ng-container *ngIf="showAdminAreas">
    <li *ngFor="let adminArea of adminAreas" class="filter-chips__item">
      <app-chip
        label="Area"
        [value]="adminArea.name"
        (closeChip)="clearAdminAreaFilter(adminArea.id)"
      ></app-chip>
    </li>
  </ng-container>
  <li *ngIf="isDayOfWeek" class="filter-chips__item">
    <app-chip
      [label]="'Day of the week'"
      [value]="dayOfWeekValues"
      (closeChip)="onClearDayOfWeekFilter()"
    ></app-chip>
  </li>
  <li *ngIf="isTimeRange" class="filter-chips__item">
    <app-chip
      [label]="'Time range'"
      [value]="timeRange"
      (closeChip)="onClearTimeRangeFilter()"
    ></app-chip>
  </li>
  <li *ngIf="isMinDelay" class="filter-chips__item">
    <app-chip
      [label]="'Maximum early'"
      [value]="minDelay"
      (closeChip)="onClearMinDelayFilter()"
    ></app-chip>
  </li>
  <li *ngIf="isMaxDelay" class="filter-chips__item">
    <app-chip
      [label]="'Maximum late'"
      [value]="maxDelay"
      (closeChip)="onClearMaxDelayFilter()"
    ></app-chip>
  </li>
</ul>

// frontend-two/components/on-time/FilterChips.tsx
import { entries as getEntries } from "lodash-es";
import { CrossIcon } from "@/components/icons/CrossIcon";
import { RefineResultsAdminAreaOption } from "@/components/shared/RefineResults/RefineResultsFilters";
import { PerformanceFiltersInputType } from "@/src/generated/graphql";

interface FilterChipsProps {
  filters: PerformanceFiltersInputType;
  adminAreaOptions?: RefineResultsAdminAreaOption[];
  onFilterChange: (filters: PerformanceFiltersInputType) => void;
}

const dayOfWeekValueMap = {
  monday: "Mon",
  tuesday: "Tue",
  wednesday: "Wed",
  thursday: "Thur",
  friday: "Fri",
  saturday: "Sat",
  sunday: "Sun",
} as const;

const weekends = "Sat, Sun";
const weekdays = "Mon, Tue, Wed, Thur, Fri";
const DEFAULT_START_TIME = "00:00";
const DEFAULT_END_TIME = "23:59";

const getDayOfWeekValues = (filters: PerformanceFiltersInputType): string => {
  const value = getEntries(filters.dayOfWeekFlags ?? {})
    .filter(([, enabled]) => enabled)
    .map(([day]) => dayOfWeekValueMap[day as keyof typeof dayOfWeekValueMap])
    .join(", ");

  if (value === weekdays) {
    return "Weekdays";
  }

  if (value === weekends) {
    return "Weekends";
  }

  return value;
};

const FilterChip = ({
  label,
  value,
  onClear,
}: {
  label: string;
  value: string;
  onClear: () => void;
}) => {
  return (
    <div className="filter-chip">
      <button
        type="button"
        className="filter-chip__remove"
        aria-label={`Remove ${label} filter`}
        onClick={onClear}
      >
        <CrossIcon className="filter-chip__remove-icon" />
      </button>
      <span className="filter-chip__label">{label}:</span>
      <span className="filter-chip__value">{value}</span>
    </div>
  );
};

export const FilterChips = ({
  filters,
  adminAreaOptions = [],
  onFilterChange,
}: FilterChipsProps) => {
  const isAdminAreas = Boolean(filters.adminAreaIds?.length);
  const isDayOfWeek = Boolean(filters.dayOfWeekFlags);
  const isTimeRange = Boolean(filters.startTime) || Boolean(filters.endTime);
  const isMinDelay = Boolean(filters.minDelay);
  const isMaxDelay = Boolean(filters.maxDelay);

  if (
    !isAdminAreas &&
    !isDayOfWeek &&
    !isTimeRange &&
    !isMinDelay &&
    !isMaxDelay
  ) {
    return null;
  }

  const adminAreaNameById = new Map(
    adminAreaOptions.map((option) => [option.value, option.label]),
  );

  const updateFilters = (nextFilters: PerformanceFiltersInputType) => {
    onFilterChange(nextFilters);
  };

  const clearDayOfWeekFilter = () => {
    const { dayOfWeekFlags: _, ...rest } = filters;
    updateFilters(rest);
  };

  const clearAdminAreaFilter = (adminAreaId: string) => {
    updateFilters({
      ...filters,
      adminAreaIds: filters.adminAreaIds?.filter((id) => id !== adminAreaId),
    });
  };

  const clearTimeRangeFilter = () => {
    const { startTime: _, endTime: __, ...rest } = filters;
    updateFilters(rest);
  };

  const clearMinDelayFilter = () => {
    const { minDelay: _, ...rest } = filters;
    updateFilters(rest);
  };

  const clearMaxDelayFilter = () => {
    const { maxDelay: _, ...rest } = filters;
    updateFilters(rest);
  };

  const timeRange = `${filters.startTime ?? DEFAULT_START_TIME} - ${filters.endTime ?? DEFAULT_END_TIME}`;
  const minDelay = filters.minDelay ? `${filters.minDelay * -1} minutes` : "";
  const maxDelay = filters.maxDelay ? `${filters.maxDelay} minutes` : "";

  return (
    <ul className="filter-chips" aria-label="Active filters">
      {filters.adminAreaIds?.map((adminAreaId) => (
        <li className="filter-chips__item" key={adminAreaId}>
          <FilterChip
            label="Area"
            value={adminAreaNameById.get(adminAreaId) ?? adminAreaId}
            onClear={() => clearAdminAreaFilter(adminAreaId)}
          />
        </li>
      ))}

      {isDayOfWeek && (
        <li className="filter-chips__item">
          <FilterChip
            label="Day of the week"
            value={getDayOfWeekValues(filters)}
            onClear={clearDayOfWeekFilter}
          />
        </li>
      )}

      {isTimeRange && (
        <li className="filter-chips__item">
          <FilterChip
            label="Time range"
            value={timeRange}
            onClear={clearTimeRangeFilter}
          />
        </li>
      )}

      {isMinDelay && (
        <li className="filter-chips__item">
          <FilterChip
            label="Maximum early"
            value={minDelay}
            onClear={clearMinDelayFilter}
          />
        </li>
      )}

      {isMaxDelay && (
        <li className="filter-chips__item">
          <FilterChip
            label="Maximum late"
            value={maxDelay}
            onClear={clearMaxDelayFilter}
          />
        </li>
      )}
    </ul>
  );
};
