// frontend-two/components/shared/Status.tsx
interface StatusProps {
  active?: boolean;
  size?: "small" | "medium" | "large";
  label?: boolean;
}

export const Status = ({
  active,
  size = "small",
  label = true,
}: StatusProps) => {
  const status = active ? "active" : "inactive";
  const icon = active
    ? "check-in-circle-solid.svg"
    : "cross-in-circle-solid.svg";

  return (
    <div className={`status status--${status} status--${size}`}>
      <img
        className="status__icon"
        src={`/assets/icons/${icon}`}
        alt=""
        aria-hidden="true"
      />
      {label ? (
        <span className="status__label">{status}</span>
      ) : (
        <span className="govuk-visually-hidden">{status}</span>
      )}
    </div>
  );
};

// frontend/src/app/shared/components/status/status.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-status",
  templateUrl: "./status.component.html",
  styleUrls: ["./status.component.scss"],
})
export class StatusComponent {
  @Input() active?: boolean;
  @Input() size?: "small" | "medium" | "large";
  @Input() label = true;

  get svgSrc() {
    return `/assets/icons/${this.active ? "check" : "cross"}-in-circle-solid.svg`;
  }

  get status() {
    return this.active ? "active" : "inactive";
  }

  get statusClasses() {
    return {
      status: true,
      [`status--${this.active ? "active" : "inactive"}`]:
        this.active !== undefined,
      [`status--${this.size}`]: this.size,
    };
  }
}

<div [ngClass]="statusClasses">
  <svg-icon
    class="status__icon"
    [applyClass]="true"
    [src]="svgSrc"
    aria-hidden="true"
  ></svg-icon>
  <span *ngIf="label" class="status__label">{{ status }}</span>
  <span *ngIf="!label" class="govuk-visually-hidden">{{ status }}</span>
</div>
