// frontend-two/components/on-time/otp-threshold/OtpThresholdModal.tsx
import { useEffect, useState } from "react";
import { Modal } from "@/components/shared/Modal";
import {
  OtpThresholdForm,
  OtpThresholds,
} from "@/components/on-time/otp-threshold/OtpThresholdForm";
import {
  PerformanceParams,
  PunctualityOverview,
  onTimeService,
} from "@/services/on-time/on-time.service";

interface OtpThresholdModalProps {
  open: boolean;
  onClose: () => void;
  /** Current on-time query params; the comparison re-runs the stats query with these plus custom thresholds. */
  params: PerformanceParams | null;
  /** The current punctuality overview, used to populate the "Default" column. */
  defaultValues?: PunctualityOverview | null;
}

const ratio = (
  value?: number | null,
  completed?: number | null,
): number | null => {
  if (value == null || !completed) return null;
  return value / completed;
};

const formatRatio = (value: number | null, fallback: string): string =>
  value == null ? fallback : `${(value * 100).toFixed(2)}%`;

interface ComparisonRow {
  key: string;
  label: string;
  defaultRatio: number | null;
  comparisonRatio: number | null;
}

/**
 * Modal that lets the user compare on-time performance against an alternative
 * definition of "on-time" (custom early / late minute thresholds).
 * Mirrors the Angular otp-threshold-modal.
 */
export const OtpThresholdModal = ({
  open,
  onClose,
  params,
  defaultValues,
}: OtpThresholdModalProps) => {
  const [comparison, setComparison] = useState<PunctualityOverview | null>(
    null,
  );
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reset the comparison whenever the modal is closed.
  useEffect(() => {
    if (!open) {
      setComparison(null);
      setError(null);
      setLoading(false);
    }
  }, [open]);

  const handleCompare = async ({ early, late }: OtpThresholds) => {
    if (!params) return;
    setLoading(true);
    setError(null);
    try {
      const data = await onTimeService.fetchOnTimeStats({
        ...params,
        filters: {
          ...params.filters,
          onTimeMaxMinutes: late,
          onTimeMinMinutes: early * -1,
        },
      });
      setComparison(data);
    } catch {
      setError("There was an issue comparing data, please try again.");
      setComparison(null);
    } finally {
      setLoading(false);
    }
  };

  const rows: ComparisonRow[] = [
    {
      key: "onTime",
      label: "On time",
      defaultRatio: ratio(defaultValues?.onTime, defaultValues?.completed),
      comparisonRatio: ratio(comparison?.onTime, comparison?.completed),
    },
    {
      key: "late",
      label: "Late",
      defaultRatio: ratio(defaultValues?.late, defaultValues?.completed),
      comparisonRatio: ratio(comparison?.late, comparison?.completed),
    },
    {
      key: "early",
      label: "Early",
      defaultRatio: ratio(defaultValues?.early, defaultValues?.completed),
      comparisonRatio: ratio(comparison?.early, comparison?.completed),
    },
  ];

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Compare on-time performance thresholds"
      description="Use an alternative definition of on-time to compare performance data with other platforms."
    >
      {error ? (
        <p className="govuk-error-message">
          <span className="govuk-visually-hidden">Error:</span> {error}
        </p>
      ) : null}

      <OtpThresholdForm onCompare={handleCompare} />

      <table className="govuk-table">
        <thead className="govuk-table__head">
          <tr className="govuk-table__row">
            <th scope="col" className="govuk-table__header">
              <span className="govuk-visually-hidden">Metric</span>
            </th>
            <th
              scope="col"
              className="govuk-table__header govuk-table__header--numeric"
            >
              Default
            </th>
            <th
              scope="col"
              className="govuk-table__header govuk-table__header--numeric"
            >
              Comparison
            </th>
          </tr>
        </thead>
        <tbody className="govuk-table__body">
          {rows.map((row) => (
            <tr key={row.key} className="govuk-table__row">
              <th scope="row" className="govuk-table__header">
                {row.label}
              </th>
              <td className="govuk-table__cell govuk-table__cell--numeric">
                {formatRatio(row.defaultRatio, "Unavailable")}
              </td>
              <td className="govuk-table__cell govuk-table__cell--numeric">
                {loading ? (
                  <span className="govuk-visually-hidden">Loading</span>
                ) : (
                  <span className="govuk-!-font-weight-bold">
                    {formatRatio(row.comparisonRatio, "-")}
                  </span>
                )}
                {loading ? <span aria-hidden="true">…</span> : null}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ display: "flex", justifyContent: "flex-end" }}>
        <button
          type="button"
          className="govuk-button govuk-button--secondary govuk-!-margin-bottom-0"
          onClick={onClose}
        >
          Close
        </button>
      </div>
    </Modal>
  );
};

// frontend/src/app/on-time/otp-threshold-modal/otp-threshold-modal.component.ts
import { AfterViewInit, Component, OnDestroy } from "@angular/core";
import { NgxSmartModalComponent, NgxSmartModalService } from "ngx-smart-modal";
import { Subject, takeUntil } from "rxjs";
import { FormErrors } from "../../shared/gds/error-summary/error-summary.component";
import {
  OnTimeService,
  PerformanceParams,
  PunctualityOverview,
} from "../on-time.service";
import { OtpThresholdParams } from "../otp-threshold-form/otp-threshold-form.component";

export const OTP_THRESHOLD_MODAL_ID = "otp-threshold-modal";

export interface OtpThresholdModalData {
  params: PerformanceParams | null;
  defaultValues?: PunctualityOverview;
}

interface OtpThresholdComparisonData {
  name: string;
  defaultValue: number | null;
  comparisonValue: number | null;
}

interface OtpThresholdTableData {
  onTime: OtpThresholdComparisonData;
  late: OtpThresholdComparisonData;
  early: OtpThresholdComparisonData;
}

@Component({
  selector: "app-otp-threshold-modal",
  templateUrl: "./otp-threshold-modal.component.html",
  styleUrls: ["./otp-threshold-modal.component.scss"],
})
export class OtpThresholdModalComponent implements AfterViewInit, OnDestroy {
  identifier = OTP_THRESHOLD_MODAL_ID;
  tableData: OtpThresholdTableData = {
    onTime: { name: "On time", defaultValue: null, comparisonValue: null },
    late: { name: "Late", defaultValue: null, comparisonValue: null },
    early: { name: "Early", defaultValue: null, comparisonValue: null },
  };
  orderBy = () => 0;
  params!: PerformanceParams;

  loading = false;
  errors: FormErrors[] = [];

  constructor(
    private modalService: NgxSmartModalService,
    private onTimeService: OnTimeService,
  ) {}

  private destroy$ = new Subject<void>();

  ngAfterViewInit(): void {
    const modal = this.modalService.getModal(OTP_THRESHOLD_MODAL_ID);

    modal.onOpen
      .pipe(takeUntil(this.destroy$))
      .subscribe((modal: NgxSmartModalComponent) => {
        const data = modal.getData() as OtpThresholdModalData;
        const completed = data.defaultValues?.completed;

        this.tableData.onTime.defaultValue = this.setOtpValue(
          data.defaultValues?.onTime,
          completed,
        );
        this.tableData.early.defaultValue = this.setOtpValue(
          data.defaultValues?.early,
          completed,
        );
        this.tableData.late.defaultValue = this.setOtpValue(
          data.defaultValues?.late,
          completed,
        );
        this.params = data.params as PerformanceParams;
      });

    modal.onAnyCloseEvent.subscribe(() => {
      this.onDestroy();
    });
  }

  ngOnDestroy(): void {
    this.onDestroy();
  }

  closeModal() {
    this.modalService.close(OTP_THRESHOLD_MODAL_ID);
  }

  onCompare(thresholds: OtpThresholdParams) {
    this.loading = true;
    this.errors = [];
    this.onTimeService
      .fetchOnTimeStats({
        ...this.params,
        filters: {
          ...this.params.filters,
          onTimeMaxMinutes: thresholds.late,
          onTimeMinMinutes: thresholds.early * -1,
        },
      })
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (data) => {
          this.tableData.onTime.comparisonValue = this.setOtpValue(
            data.onTime,
            data.completed,
          );
          this.tableData.early.comparisonValue = this.setOtpValue(
            data.early,
            data.completed,
          );
          this.tableData.late.comparisonValue = this.setOtpValue(
            data.late,
            data.completed,
          );
          this.loading = false;
        },
        error: () => {
          this.errors = [
            { error: "There was an issue comparing data, please try again." },
          ];
          this.loading = false;
        },
      });
  }

  private setOtpValue(
    value: number | undefined,
    completed: number | undefined,
  ): number | null {
    if (value !== undefined && completed !== undefined) {
      return value / completed;
    }
    return null;
  }

  private onDestroy() {
    this.loading = false;
    this.errors = [];
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<app-modal
  modalTitle="Compare on-time performance thresholds"
  [identifier]="identifier"
>
  <gds-error-summary [errors]="errors"></gds-error-summary>
  <p class="govuk-body">
    Use an alternative definition of on-time to compare performance data with
    other platforms.
  </p>
  <app-otp-threshold-form
    (compare)="onCompare($event)"
  ></app-otp-threshold-form>
  <table class="govuk-table">
    <thead class="govuk-table__head">
      <tr class="govuk-table__row">
        <th scope="col" class="govuk-table__header"></th>
        <th
          scope="col"
          class="govuk-table__header govuk-table__header--numeric"
        >
          Default
        </th>
        <th
          scope="col"
          class="govuk-table__header govuk-table__header--numeric"
        >
          Comparison
        </th>
      </tr>
    </thead>
    <tbody class="govuk-table__body">
      <tr
        *ngFor="let item of tableData | keyvalue: orderBy"
        class="govuk-table__row"
      >
        <th scope="row" class="govuk-table__header">{{ item.value.name }}</th>
        <td class="govuk-table__cell govuk-table__cell--numeric">
          {{
            (item.value.defaultValue | noInfinity | percent: "1.0-2") ||
              "Unavailable"
          }}
        </td>
        <td class="govuk-table__cell govuk-table__cell--numeric">
          <span
            *ngIf="!loading; else skeleton"
            class="govuk-!-font-weight-bold"
            >{{
              (item.value.comparisonValue | noInfinity | percent: "1.0-2") ||
                "-"
            }}</span
          >
          <ng-template #skeleton
            ><app-skeleton
              appearance="body"
              width="80px"
              spaceBelow="0"
              [style.float]="'right'"
            ></app-skeleton
          ></ng-template>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="flex-row-reverse">
    <gds-button
      text="Close"
      appearance="secondary"
      spaceBelow="0"
      type="button"
      (click)="closeModal()"
    ></gds-button>
  </div>
</app-modal>
