// frontend-two/components/dashboard/VehiclesStatus.tsx
import { Box } from "@/components/shared/Box";
import { Stat } from "@/components/shared/Stat";
import { LinkWithArrow } from "@/components/shared/LinkWithArrow";

interface VehiclesStatusProps {
  actual: number;
  expected: number;
  nocCode: string | null;
}

export const VehiclesStatus = ({
  actual,
  expected,
  nocCode,
}: VehiclesStatusProps) => {
  const liveStatusHref = nocCode
    ? `/feed-monitoring/${nocCode}`
    : "/feed-monitoring";

  return (
    <Box className="app-vehicles-status">
      <h2 className="govuk-heading-m">Vehicle count</h2>
      <div className="vehicles-status__stats">
        <Stat
          label="Current"
          value={actual}
          id="vehicle-status-current"
          className="vehicles-status__current-stat"
          tooltip="Current number of vehicles running that we can match to the schedules that have been provided"
        />
        <Stat
          label="Expected"
          value={expected}
          id="vehicle-status-expected"
          className="vehicles-status__expected-stat"
          tooltip="The number of vehicles that should be running now according to the timetables provided"
        />
      </div>
      <div className="vehicles-status__footer">
        <LinkWithArrow href={liveStatusHref}>Live status</LinkWithArrow>
      </div>
    </Box>
  );
};

// frontend/src/app/dashboard/vehicles-status/vehicles-status.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-vehicles-status",
  templateUrl: "./vehicles-status.component.html",
  styleUrls: ["./vehicles-status.component.scss"],
})
export class VehiclesStatusComponent {
  @Input() expected?: number | null;
  @Input() actual?: number | null;
  @Input() nocCode?: string | null;

  get liveStatusRoute() {
    if (this.nocCode) {
      return ["/feed-monitoring", this.nocCode];
    }

    return ["/feed-monitoring"];
  }
}

<app-box>
  <!-- <h2 class="govuk-heading-m">Live Vehicles status</h2> -->
  <h2 class="govuk-heading-m">Vehicle count</h2>
  <div class="vehicles-status__stats">
    <!-- <p style="margin-left: 15px; margin-top: 5px">Under Maintenance</p> -->
    <app-stat
      label="Current"
      [statValue]="actual"
      id="vehicle-status-current"
      class="vehicles-status__current-stat"
      tooltip="Current number of vehicles running that we can match to the schedules that have been provided"
    ></app-stat>
    <app-stat
      label="Expected"
      [statValue]="expected"
      id="vehicle-status-expected"
      class="vehicles-status__expected-stat"
      tooltip="The number of vehicles that should be running now according to the timetables provided"
    ></app-stat>
  </div>

  <div class="vehicles-status__footer">
    <app-link
      [route]="liveStatusRoute"
      [arrows]="true"
      [underline]="false"
      weight="bold"
      >Live status</app-link
    >
  </div>
</app-box>
