// frontend-two/pages/feed-monitoring/[nocCode]/feed-history.tsx
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import dynamic from "next/dynamic";
import { DateTime } from "luxon";
import { BaseLayout } from "@/components/layout/BaseLayout";
import { useConfig } from "@/contexts/ConfigContext";
import { feedMonitoringService } from "@/services/feed-monitoring/feed-monitoring.services";
import {
  FeedMonitoringListQuery,
  OperatorHistoricStatsQuery,
} from "../../../src/generated/graphql";
import { Box } from "@/components/shared/Box";
import { Spinner } from "@/components/shared/Spinner";
import { SummaryStatWithTooltip } from "@/components/shared/SummaryStat/SummaryStatWithTooltip";
import { OperatorDropdown } from "@/components/feed-monitoring/OperatorDropdown";
import { DateNavigationDayBlocks } from "@/components/shared/DateNavigationDayBlocks/DateNavigationDayBlocks";
import { useHelpdesk } from "@/contexts/HelpdeskContext";
import { useRequireAuth } from "@/hooks/useAuth";
import ExclamationInCircleIcon from "@/assets/icons/exclamation-in-circle.svg";
import styles from "@/components/feed-monitoring/feed-history.module.scss";

const HistoricVehicleStats = dynamic(
  () => import("@/components/feed-monitoring/HistoricVehicleStats"),
  { ssr: false },
);

type FeedMonitoringOperatorData =
  FeedMonitoringListQuery["operatorsFeedMonitoring"][number];
type OperatorFeedHistory = OperatorHistoricStatsQuery["operatorFeedMonitoring"];

function buildDateList(): { date: DateTime }[] {
  const yesterday = DateTime.now().startOf("day").minus({ days: 1 });
  const startDate = yesterday.minus({ months: 3 }).plus({ days: 1 });
  const days = Math.floor(yesterday.diff(startDate, "days").days) + 1;
  return Array.from({ length: days }, (_, i) => ({
    date: startDate.plus({ days: i }),
  }));
}

function formatAvailability(f?: number | null): string {
  if (f === undefined || f === null) return "0.00%";
  return `${(f * 100).toFixed(2)}%`;
}

function formatUpdateFrequency(f?: number | null): string {
  return f ? `${f}s` : "-";
}

function FeedHistoryEmptyState({ message }: { message: string }) {
  return (
    <Box minHeight="385px" className={styles.emptyStateBox}>
      <div className={styles.emptyState}>
        <ExclamationInCircleIcon
          className={styles.emptyStateIcon}
          aria-hidden="true"
          focusable="false"
        />
        <p className="govuk-body">{message}</p>
      </div>
    </Box>
  );
}

const FeedHistoryPage = () => {
  useRequireAuth();
  const { loadData } = useHelpdesk();

  useEffect(() => {
    loadData("feedMonitoring", "NOC feed monitoring");
  }, [loadData]);

  const router = useRouter();

  const { nocCode, date } = (router.query ?? {}) as {
    nocCode?: string;
    date?: string;
  };

  const yesterday = useMemo(
    () => DateTime.now().startOf("day").minus({ days: 1 }),
    [],
  );
  const baseDate = useMemo(
    () =>
      date && DateTime.fromISO(date).isValid
        ? DateTime.fromISO(date).startOf("day")
        : yesterday,
    [date, yesterday],
  );
  const formattedDate = baseDate.toFormat("d MMMM yyyy");

  const prevDate = baseDate.minus({ days: 1 });
  const nextDate = baseDate.plus({ days: 1 });
  const isNextDisabled = nextDate > yesterday;

  const { config } = useConfig();
  const [operators, setOperators] = useState<FeedMonitoringOperatorData[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [dateList, setDateList] = useState<{ date: DateTime }[]>([]);
  const [operatorHistory, setOperatorHistory] =
    useState<OperatorFeedHistory | null>(null);
  const [historicalDataLoading, setHistoricalDataLoading] = useState(false);
  const [chartErrored, setChartErrored] = useState(false);
  const [noData, setNoData] = useState(false);
  const [error, setError] = useState(false);

  useEffect(() => {
    const load = async () => {
      setIsLoading(true);
      try {
        const feedMonitoringData =
          await feedMonitoringService.fetchFeedMonitoringList();
        setOperators(feedMonitoringData);
      } catch (err) {
        console.error("Failed to load feed monitoring list data:", err);
        setError(true);
      } finally {
        setIsLoading(false);
      }
    };
    load();
  }, []);

  // Fetch historical operator stats for selected date
  useEffect(() => {
    // Create date array for DateNavigation component
    setDateList(buildDateList());

    if (!nocCode || !baseDate.isValid) return;
    setHistoricalDataLoading(true);
    setChartErrored(false);
    setNoData(false);

    const start = baseDate.startOf("day").toISO()!;
    const end = baseDate.endOf("day").toISO()!;

    const load = async () => {
      try {
        const operatorHistoryData =
          await feedMonitoringService.fetchOperatorHistory(
            nocCode,
            baseDate.toISODate()!,
            start,
            end,
          );
        setHistoricalDataLoading(false);
        if (!operatorHistoryData) {
          setChartErrored(true);
        } else if (
          (operatorHistoryData.feedMonitoring?.vehicleStats?.length ?? 0) === 0
        ) {
          setNoData(true);
        }
        setOperatorHistory(operatorHistoryData);
      } catch (err) {
        console.error("Failed to load operator history data:", err);
        setHistoricalDataLoading(false);
        setChartErrored(true);
      }
    };
    load();
  }, [nocCode, baseDate]);

  if (isLoading) {
    return (
      <BaseLayout title="Feed history - Analyse Bus Open Data">
        <div className="feed-monitoring-page">
          <p className="govuk-body">Loading...</p>
        </div>
      </BaseLayout>
    );
  }

  const vehicleStats = operatorHistory?.feedMonitoring?.vehicleStats ?? [];
  const availability =
    operatorHistory?.feedMonitoring?.historicalStats?.availability;
  const updateFrequency =
    operatorHistory?.feedMonitoring?.historicalStats?.updateFrequency;

  return (
    <BaseLayout
      title="Feed history - Analyse Bus Open Data"
      backLink={
        <Link
          href={`/feed-monitoring/${nocCode}`}
          className="govuk-back-link back-link govuk-!-margin-bottom-0"
        >
          Live status
        </Link>
      }
    >
      <div className="feed-monitoring-page">
        <div>
          {error && (
            <div
              className="govuk-error-summary"
              role="alert"
              aria-labelledby="error-summary-title"
            >
              <h2
                className="govuk-error-summary__title"
                id="error-summary-title"
              >
                There is a problem
              </h2>
              <div className="govuk-error-summary__body">
                <p className="govuk-body">
                  There was a problem loading the feed history data. Please try
                  refreshing the page.
                </p>
              </div>
            </div>
          )}
          <header className="govuk-!-margin-bottom-2">
            <span className="govuk-caption-xl">NOC feed monitoring</span>
            <h1 className="govuk-heading-xl app-page-header">Feed history</h1>
          </header>
          <div className="flex items-baseline gap-4">
            <span
              className="govuk-body"
              style={{ color: "#484949", fontSize: "24px" }}
            >{`Operator`}</span>
            <OperatorDropdown
              operators={operators}
              currentNocCode={nocCode ?? ""}
              pageLink={`/feed-monitoring/[nocCode]/feed-history?date=${date ?? ""}`}
            />
          </div>
        </div>
        <div className="flex items-center justify-between mt-8">
          <span className="font-bold" style={{ fontSize: "24px" }}>
            {formattedDate}
          </span>
          <div className="flex gap-8">
            <a
              href={`/feed-monitoring/${nocCode}/feed-history?date=${prevDate.toISODate()}`}
              className="govuk-link"
              style={{ fontWeight: "bold", fontSize: "16px" }}
            >
              ‹ Previous
            </a>
            {isNextDisabled ? (
              <span
                className="govuk-link govuk-link--disabled"
                style={{
                  fontWeight: "bold",
                  fontSize: "16px",
                  color: "#b1b4b6",
                  pointerEvents: "none",
                  cursor: "not-allowed",
                }}
              >
                Next ›
              </span>
            ) : (
              <a
                href={`/feed-monitoring/${nocCode}/feed-history?date=${nextDate.toISODate()}`}
                className="govuk-link"
                style={{ fontWeight: "bold", fontSize: "16px" }}
              >
                Next ›
              </a>
            )}
          </div>
        </div>
        <DateNavigationDayBlocks
          dateArray={dateList}
          selectedDate={baseDate}
          onDateSelected={(selectedDate) => {
            router.push(
              `/feed-monitoring/${nocCode}/feed-history?date=${selectedDate.toISODate()}`,
            );
          }}
        />
        <div className="mt-4">
          {historicalDataLoading && (
            <Box minHeight="385px">
              <Spinner size="default" message="Loading..." vCentre />
            </Box>
          )}
          {!historicalDataLoading && chartErrored && (
            <FeedHistoryEmptyState message="There was an error loading the chart data, please try again." />
          )}
          {!historicalDataLoading && noData && (
            <FeedHistoryEmptyState message="No data found for the date selected." />
          )}
          {!historicalDataLoading &&
            !chartErrored &&
            !noData &&
            vehicleStats.length > 0 && (
              <Box>
                <HistoricVehicleStats data={vehicleStats} date={baseDate} />
              </Box>
            )}
        </div>
        <div className="grid grid-cols-4 gap-4 mt-6">
          <SummaryStatWithTooltip
            title="Feed availability"
            value={
              historicalDataLoading ? "-" : formatAvailability(availability)
            }
            tooltip="The percentage of the day the feed was active when vehicles were expected to be running"
          />
          <SummaryStatWithTooltip
            title="Average update frequency"
            value={
              historicalDataLoading
                ? "-"
                : formatUpdateFrequency(updateFrequency)
            }
          />
        </div>
      </div>
    </BaseLayout>
  );
};
export default FeedHistoryPage;

// frontend/src/app/feed-monitoring/feed-history/feed-history.component.ts
import { ViewportScroller } from "@angular/common";
import { ChangeDetectorRef, Component, OnDestroy, OnInit } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { DateTime } from "luxon";
import { combineLatest, of, Subject } from "rxjs";
import {
  catchError,
  delay,
  distinctUntilChanged,
  filter,
  map,
  switchMap,
  takeUntil,
  tap,
} from "rxjs/operators";
import {
  AlertTypeEnum,
  OperatorFeedHistoryFragment,
  VehicleStatsType,
} from "src/generated/graphql";
import { nonNullishArray } from "../../shared/array-operators";
import {
  AlertListViewModel,
  AlertMode,
} from "../alert-list/alert-list-view-model";
import { EventStats, FeedMonitoringService } from "../feed-monitoring.service";
import { IHeatmap } from "./datenav/datenav.component";

@Component({
  selector: "app-history",
  templateUrl: "./feed-history.component.html",
  styleUrls: ["./feed-history.component.scss"],
})
export class FeedHistoryComponent implements OnInit, OnDestroy {
  constructor(
    private fmService: FeedMonitoringService,
    private route: ActivatedRoute,
    private router: Router,
    private viewportScroller: ViewportScroller,
    private change: ChangeDetectorRef,
  ) {}

  loading = true;
  chartErrored = false;
  notFound = false;
  noData = false;

  operator: OperatorFeedHistoryFragment | null = null;
  operatorId = "";
  allOperators?: {
    name?: string | null;
    operatorId: string;
  }[];

  date?: DateTime;

  alertStats?: IHeatmap[];
  alertMode = AlertMode;
  selectedAlert = new Subject<string | null>();

  vehicleStats?: VehicleStatsType[];

  alerts: { timestamp: DateTime; type: AlertTypeEnum; id: string }[] = [];

  private destroy$ = new Subject<void>();

  ngOnInit() {
    const noc$ = this.route.paramMap.pipe(
      filter((pm) => pm.has("nocCode")),
      map((pm) => pm.get("nocCode")!),
      distinctUntilChanged(),
    );

    const date$ = this.route.queryParamMap.pipe(
      tap((qpm) => {
        if (!qpm.has("date")) {
          this.router
            .navigate(["."], {
              relativeTo: this.route,
              queryParams: {
                date: DateTime.local().minus({ day: 1 }).toFormat("yyyy-MM-dd"),
              },
              replaceUrl: true,
              queryParamsHandling: "merge",
            })
            .catch(console.log);
        }
      }),
      filter((qpm) => qpm.has("date")),
      map((qpm) => DateTime.fromISO(qpm.get("date")!)),
      distinctUntilChanged(),
    );

    date$
      .pipe(takeUntil(this.destroy$))
      .subscribe((date) => (this.date = date));

    const operatorData$ = noc$.pipe(
      switchMap((noc) =>
        this.fmService.listOperators.pipe(
          map((allOperators) => {
            const operatorId =
              allOperators?.find((operator) => operator.operatorId === noc)
                ?.operatorId || "";
            return {
              allOperators: allOperators,
              noc: noc,
              operatorId: operatorId,
            };
          }),
        ),
      ),
    );

    operatorData$
      .pipe(
        switchMap((opData) =>
          this.fmService
            .fetchAlertStats(
              opData.operatorId,
              DateTime.local().toUTC().minus({ day: 1 }),
            )
            .pipe(
              map((data) => ({
                ...opData,
                stats: this.cleanUpAlertStats(data),
              })),
            ),
        ),
        takeUntil(this.destroy$),
      )
      .subscribe(({ operatorId, allOperators, stats }) => {
        this.operatorId = operatorId;
        this.allOperators = allOperators;
        this.alertStats = stats;
      });

    combineLatest([operatorData$, date$])
      .pipe(
        filter(([_, date]) => !!date),
        tap(() => {
          this.chartErrored = false;
          this.notFound = false;
          this.noData = false;
          this.loading = true;
        }),
        switchMap(([{ operatorId }, date]) =>
          this.fmService.fetchOperatorHistory(operatorId, date),
        ),
        catchError(() => {
          this.chartErrored = true;
          return of(null);
        }),
        takeUntil(this.destroy$),
      )
      .subscribe((operator) => {
        this.loading = false;
        this.operator = operator;

        if (!operator) {
          this.notFound = true;
        } else if ((operator.feedMonitoring?.vehicleStats?.length ?? 0) > 0) {
          this.chartErrored = false;
          this.vehicleStats = nonNullishArray(
            operator.feedMonitoring?.vehicleStats,
          );
        } else {
          this.noData = true;
        }
      });

    this.selectedAlert
      .pipe(
        filter((alert) => alert !== null),
        delay(5000),
        takeUntil(this.destroy$),
      )
      .subscribe(() => this.selectedAlert.next(null));
  }

  private cleanUpAlertStats(
    stats: EventStats[],
  ): { heat: number; date: DateTime }[] {
    const max: number = Math.max(...stats.map(({ count }) => count ?? 0));

    return stats.map(({ count, day }) => ({
      heat: count ? Math.ceil((count / max) * 6) : 0,
      date: DateTime.fromISO(day),
    }));
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  changeOperator({ nocCode }: { nocCode: string }) {
    this.router
      .navigate(["/", "feed-monitoring", nocCode, "feed-history"])
      .catch(console.log);
  }

  changeDate(date: DateTime) {
    this.router
      .navigate(["."], {
        relativeTo: this.route,
        queryParams: { date: date.toISODate() },
        queryParamsHandling: "merge",
      })
      .catch(console.log);
  }

  formatUpdateFrequency(f?: number) {
    return f ? `${f}s` : "-";
  }

  formatAvailability(f?: number) {
    if (f === undefined || f === null) return "0.00%";
    return `${(f * 100).toFixed(2)}%`;
  }

  newAlerts(alerts: AlertListViewModel[]) {
    this.alerts = alerts ?? [];
  }

  alertSelected(id: string) {
    this.selectedAlert.next(id);
    // this will be called from outside the angular zone (in amCharts) so manually invoke change detection:
    this.change.detectChanges();
    this.viewportScroller.scrollToAnchor(id);
  }
}

<app-page *ngIf="!(notFound && !chartErrored); else operatorNotFound"
  ><ng-container ngProjectAs="back-link">
    <gds-back-link label="Live status"></gds-back-link>
  </ng-container>
  <ng-container ngProjectAs="content">
    <app-page-header
      caption="NOC feed monitoring"
      heading="Feed history"
      spaceBelow="2"
    ></app-page-header>

    <app-operator-selector
      [allOperators]="allOperators"
      [operator]="operator"
      (operatorChange)="changeOperator($event)"
    ></app-operator-selector>

    <app-datenav
      [stats]="alertStats"
      [date]="date"
      (dateSelected)="changeDate($event)"
    ></app-datenav>

    <app-historic-vehicle-stats
      *ngIf="!chartErrored && !noData && !loading"
      chartId="historic-vehicle-stats"
      [dataSource]="vehicleStats"
      [alertsDataSource]="alerts"
      [date]="date"
      (alertSelected)="alertSelected($event)"
    ></app-historic-vehicle-stats>

    <app-box *ngIf="loading" minHeight="385px">
      <app-spinner
        [vCentre]="true"
        message="Loading..."
        size="default"
      ></app-spinner>
    </app-box>

    <app-box *ngIf="chartErrored" minHeight="385px">
      <div class="feed-history--error">
        <svg-icon
          class="feed-history--error__icon"
          src="assets/icons/exclamation-in-circle.svg"
          [applyClass]="true"
        ></svg-icon>
        <span class="feed-history--error__message"
          >There was an error loading the chart data, please try again.</span
        >
      </div>
    </app-box>

    <app-box *ngIf="noData" minHeight="385px">
      <div class="feed-history--error">
        <svg-icon
          class="feed-history--error__icon"
          src="assets/icons/exclamation-in-circle.svg"
          [applyClass]="true"
        ></svg-icon>
        <span class="feed-history--error__message"
          >No data found for the date selected.</span
        >
      </div>
    </app-box>

    <div class="govuk-grid-row feed-history__stats">
      <app-stat
        label="Feed availability"
        class="feed-history__stat feed-history__availability"
        [statValue]="
          operator?.feedMonitoring?.historicalStats?.availability || 0
        "
        [statFormatter]="formatAvailability"
        [statLoaded]="!loading"
        tooltip="The percentage of the day the feed was active when vehicles were expected to be running"
        id="historic-stat-availability"
      ></app-stat>
      <app-stat
        label="Average update frequency"
        class="feed-history__stat feed-history__update-frequency"
        [statValue]="
          operator?.feedMonitoring?.historicalStats?.updateFrequency || 0
        "
        [statFormatter]="formatUpdateFrequency"
        [statLoaded]="!loading"
        id="historic-stat-frequency"
      ></app-stat>
    </div>

    <app-alert-list
      *ngIf="operatorId"
      [date]="date"
      [mode]="alertMode.FeedHistory"
      [operatorId]="operatorId"
      [selectedId]="selectedAlert | async"
      (alerts)="newAlerts($event)"
      style="display: none"
    ></app-alert-list>
  </ng-container>
</app-page>

<ng-template #operatorNotFound>
  <app-page>
    <ng-container ngProjectAs="back-link">
      <gds-back-link label="NOC feed monitoring"></gds-back-link>
    </ng-container>
    <ng-container ngProjectAs="content">
      <app-page-header
        caption="NOC feed monitoring"
        heading="Not found"
      ></app-page-header>
      <p class="govuk-body">
        Operator not found, or you do not have permission to view. Go back to
        <a [routerLink]="['/feed-monitoring']">NOC feed monitoring</a>?
      </p>
    </ng-container>
  </app-page>
</ng-template>
