// frontend/src/app/shared/components/filter-chips/filter-chips.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { entries as _entries } from "lodash-es";
import { PerformanceFiltersInputType } from "../../../../generated/graphql";

export interface DayOfWeekLabel {
  monday: "Mon";
  tuesday: "Tue";
  wednesday: "Wed";
  thursday: "Thur";
  friday: "Fri";
  saturday: "Sat";
  sunday: "Sun";
}

@Component({
  selector: "app-filter-chips",
  templateUrl: "./filter-chips.component.html",
  styleUrls: ["./filter-chips.component.scss"],
})
export class FilterChipsComponent {
  @Input() enableChip = false;
  @Input() filters: PerformanceFiltersInputType = {};
  @Output() filterChange = new EventEmitter<PerformanceFiltersInputType>();

  get isDayOfWeek(): boolean {
    return !!this.filters.dayOfWeekFlags;
  }

  get isTimeRange(): boolean {
    return !!this.filters.startTime || !!this.filters.endTime;
  }

  get isMinDelay(): boolean {
    return !!this.filters.minDelay;
  }

  get isMaxDelay(): boolean {
    return !!this.filters.maxDelay;
  }

  dayOfWeekValueMap: DayOfWeekLabel = {
    monday: "Mon",
    tuesday: "Tue",
    wednesday: "Wed",
    thursday: "Thur",
    friday: "Fri",
    saturday: "Sat",
    sunday: "Sun",
  };

  private readonly weekends = "Sat, Sun";
  private readonly weekdays = "Mon, Tue, Wed, Thur, Fri";

  get dayOfWeekValues(): string {
    const value = _entries(this.filters.dayOfWeekFlags ?? {})
      .filter(([, value]) => value)
      .map(([day]) => this.dayOfWeekValueMap[day as keyof DayOfWeekLabel])
      .join(", ");

    if (value === this.weekdays) {
      return "Weekdays";
    }
    if (value === this.weekends) {
      return "Weekends";
    }

    return value;
  }

  get timeRange(): string {
    return this.filters.startTime + " - " + this.filters.endTime;
  }

  get minDelay(): string {
    if (this.filters.minDelay) {
      return this.filters.minDelay * -1 + " minutes";
    }
    return "";
  }

  get maxDelay(): string {
    return this.filters.maxDelay + " minutes";
  }

  onClearDayOfWeekFilter() {
    const { dayOfWeekFlags: _, ...filters } = this.filters;
    this.updateFilters(filters);
  }

  onClearTimeRangeFilter() {
    const { startTime: _, endTime: __, ...filters } = this.filters;
    this.updateFilters(filters);
  }

  onClearMinDelayFilter() {
    const { minDelay: _, ...filters } = this.filters;
    this.updateFilters(filters);
  }

  onClearMaxDelayFilter() {
    const { maxDelay: _, ...filters } = this.filters;
    this.updateFilters(filters);
  }

  updateFilters(filters: PerformanceFiltersInputType) {
    this.filters = filters;
    this.filterChange.emit(filters);
  }
}

<ul
  *ngIf="enableChip || isDayOfWeek || isTimeRange || isMinDelay || isMaxDelay"
  class="filter-chips"
>
  <ng-content></ng-content>
  <li *ngIf="isDayOfWeek" class="filter-chips__item">
    <app-chip
      [label]="'Day of the week'"
      [value]="dayOfWeekValues"
      (closeChip)="onClearDayOfWeekFilter()"
    ></app-chip>
  </li>
  <li *ngIf="isTimeRange" class="filter-chips__item">
    <app-chip
      [label]="'Time range'"
      [value]="timeRange"
      (closeChip)="onClearTimeRangeFilter()"
    ></app-chip>
  </li>
  <li *ngIf="isMinDelay" class="filter-chips__item">
    <app-chip
      [label]="'Maximum early'"
      [value]="minDelay"
      (closeChip)="onClearMinDelayFilter()"
    ></app-chip>
  </li>
  <li *ngIf="isMaxDelay" class="filter-chips__item">
    <app-chip
      [label]="'Maximum late'"
      [value]="maxDelay"
      (closeChip)="onClearMaxDelayFilter()"
    ></app-chip>
  </li>
</ul>

// frontend-two/components/on-time/FilterChips/FilterChips.tsx
import styles from "./filter-chips.module.scss";

import { entries as getEntries } from "lodash-es";
import { CrossIcon } from "@/components/icons/CrossIcon";
import { RefineResultsAdminAreaOption } from "@/components/shared/RefineResults/RefineResultsFilters";
import { PerformanceFiltersInputType } from "@/src/generated/graphql";

interface FilterChipsProps {
  filters: PerformanceFiltersInputType;
  adminAreaOptions?: RefineResultsAdminAreaOption[];
  onFilterChange: (filters: PerformanceFiltersInputType) => void;
}

const dayOfWeekValueMap = {
  monday: "Mon",
  tuesday: "Tue",
  wednesday: "Wed",
  thursday: "Thur",
  friday: "Fri",
  saturday: "Sat",
  sunday: "Sun",
} as const;

const weekends = "Sat, Sun";
const weekdays = "Mon, Tue, Wed, Thur, Fri";
const DEFAULT_START_TIME = "00:00";
const DEFAULT_END_TIME = "23:59";

const getDayOfWeekValues = (filters: PerformanceFiltersInputType): string => {
  const value = getEntries(filters.dayOfWeekFlags ?? {})
    .filter(([, enabled]) => enabled)
    .map(([day]) => dayOfWeekValueMap[day as keyof typeof dayOfWeekValueMap])
    .join(", ");

  if (value === weekdays) {
    return "Weekdays";
  }

  if (value === weekends) {
    return "Weekends";
  }

  return value;
};

const FilterChip = ({
  label,
  value,
  onClear,
}: {
  label: string;
  value: string;
  onClear: () => void;
}) => {
  return (
    <div className={styles.chip}>
      <button
        type="button"
        className={styles.remove}
        aria-label={`Remove ${label} filter`}
        onClick={onClear}
      >
        <CrossIcon className={styles.removeIcon} />
      </button>

      <span className={styles.label}>{label}:</span>

      <span className={styles.value}>{value}</span>
    </div>
  );
};

export const FilterChips = ({
  filters,
  adminAreaOptions = [],
  onFilterChange,
}: FilterChipsProps) => {
  const isAdminAreas = Boolean(filters.adminAreaIds?.length);
  const isDayOfWeek = Boolean(filters.dayOfWeekFlags);
  const isTimeRange = Boolean(filters.startTime) || Boolean(filters.endTime);
  const isMinDelay = Boolean(filters.minDelay);
  const isMaxDelay = Boolean(filters.maxDelay);

  if (
    !isAdminAreas &&
    !isDayOfWeek &&
    !isTimeRange &&
    !isMinDelay &&
    !isMaxDelay
  ) {
    return null;
  }

  const adminAreaNameById = new Map(
    adminAreaOptions.map((option) => [option.value, option.label]),
  );

  const updateFilters = (nextFilters: PerformanceFiltersInputType) => {
    onFilterChange(nextFilters);
  };

  const clearDayOfWeekFilter = () => {
    const { dayOfWeekFlags: _, ...rest } = filters;
    updateFilters(rest);
  };

  const clearAdminAreaFilter = (adminAreaId: string) => {
    updateFilters({
      ...filters,
      adminAreaIds: filters.adminAreaIds?.filter((id) => id !== adminAreaId),
    });
  };

  const clearTimeRangeFilter = () => {
    const { startTime: _, endTime: __, ...rest } = filters;
    updateFilters(rest);
  };

  const clearMinDelayFilter = () => {
    const { minDelay: _, ...rest } = filters;
    updateFilters(rest);
  };

  const clearMaxDelayFilter = () => {
    const { maxDelay: _, ...rest } = filters;
    updateFilters(rest);
  };

  const timeRange = `${filters.startTime ?? DEFAULT_START_TIME} - ${filters.endTime ?? DEFAULT_END_TIME}`;

  const minDelay = filters.minDelay ? `${filters.minDelay * -1} minutes` : "";

  const maxDelay = filters.maxDelay ? `${filters.maxDelay} minutes` : "";

  return (
    <ul className={styles.list} aria-label="Active filters">
      {filters.adminAreaIds?.map((adminAreaId) => (
        <li className={styles.listItem} key={adminAreaId}>
          <FilterChip
            label="Area"
            value={adminAreaNameById.get(adminAreaId) ?? adminAreaId}
            onClear={() => clearAdminAreaFilter(adminAreaId)}
          />
        </li>
      ))}

      {isDayOfWeek && (
        <li className={styles.listItem}>
          <FilterChip
            label="Day of the week"
            value={getDayOfWeekValues(filters)}
            onClear={clearDayOfWeekFilter}
          />
        </li>
      )}

      {isTimeRange && (
        <li className={styles.listItem}>
          <FilterChip
            label="Time range"
            value={timeRange}
            onClear={clearTimeRangeFilter}
          />
        </li>
      )}

      {isMinDelay && (
        <li className={styles.listItem}>
          <FilterChip
            label="Maximum early"
            value={minDelay}
            onClear={clearMinDelayFilter}
          />
        </li>
      )}

      {isMaxDelay && (
        <li className={styles.listItem}>
          <FilterChip
            label="Maximum late"
            value={maxDelay}
            onClear={clearMaxDelayFilter}
          />
        </li>
      )}
    </ul>
  );
};
