// frontend-two/pages/on-time/operator-not-found.tsx
import Link from "next/link";
import { BaseLayout } from "@/components/layout/BaseLayout";
import { useRequireAuth } from "@/hooks/useAuth";

const OnTimeOperatorNotFoundPage = () => {
  useRequireAuth();

  return (
    <BaseLayout title="Not found: Analyse Bus Open Data">
      <Link href="/on-time" className="govuk-back-link">
        On-time performance
      </Link>
      <span className="govuk-caption-xl">On-time performance</span>
      <h1 className="govuk-heading-xl">Not found</h1>
      <p className="govuk-body">
        Operator not found, or you do not have permission to view. Go back to{" "}
        <Link className="govuk-link" href="/on-time">
          On-time performance
        </Link>
        ?
      </p>
    </BaseLayout>
  );
};

export default OnTimeOperatorNotFoundPage;

// frontend/src/app/on-time/operator-not-found/operator-not-found.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-operator-not-found",
  templateUrl: "./operator-not-found.component.html",
})
export class OperatorNotFoundComponent {}

<app-page>
  <ng-container ngProjectAs="back-link">
    <gds-back-link
      [route]="['/on-time']"
      label="On-time performance"
    ></gds-back-link>
  </ng-container>
  <ng-container ngProjectAs="content">
    <app-page-header
      caption="On-time performance"
      heading="Not found"
    ></app-page-header>
    <p class="govuk-body">
      Operator not found, or you do not have permission to view. Go back to
      <a [routerLink]="['/on-time']">On-time performance</a>?
    </p>
  </ng-container>
</app-page>
