// frontend/src/app/authentication/login/login.component.ts
import { Component, OnDestroy, OnInit } from "@angular/core";
import {
  AbstractControl,
  FormBuilder,
  FormGroup,
  Validators,
} from "@angular/forms";
import { ActivatedRoute, Router } from "@angular/router";
import { Subject, takeUntil } from "rxjs";
import { FormErrors } from "src/app/shared/gds/error-summary/error-summary.component";
import { AuthenticationService } from "../authentication.service";
import { AuthenticatedUserService } from "../authenticated-user.service";
import { LoginResponse } from "../../../generated/graphql";

@Component({
  selector: "app-auth-login",
  templateUrl: "./login.component.html",
  standalone: false,
})
export class LoginComponent implements OnInit, OnDestroy {
  loginForm: FormGroup;
  loading = true;
  submitted = false;
  errors: FormErrors[] = [];

  private destroy$ = new Subject<void>();

  constructor(
    private formBuilder: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private authenticationService: AuthenticationService,
    private userService: AuthenticatedUserService,
  ) {
    this.loginForm = this.formBuilder.group({
      username: ["", Validators.required],
      password: ["", Validators.required],
    });
  }

  ngOnInit() {
    this.loginForm.valueChanges.pipe(takeUntil(this.destroy$)).subscribe(() => {
      this.resetForm();
    });
    const postLoginLink = this.route.snapshot.queryParams.returnUrl ?? "/";

    this.userService.loginResponse$
      .pipe(takeUntil(this.destroy$))
      .subscribe((loginResponse) => {
        if (!loginResponse?.success) {
          if (!this.submitted) {
            return;
          }
          this.errors.push({
            error: this.getErrorMessages(loginResponse),
            label: "login-username",
          });
          return;
        }
        this.loading = false;
        this.router.navigateByUrl(postLoginLink).catch(console.log);
      });
  }

  getErrorMessages(loginResponse: LoginResponse) {
    if (loginResponse.locked && loginResponse.unlockAt) {
      const unlockDate = new Date(loginResponse.unlockAt);
      const now = new Date();
      const diffMs = unlockDate.getTime() - now.getTime();
      const diffMins = Math.max(Math.ceil(diffMs / 60000), 0);

      return `Your account is locked for ${diffMins} minutes due to multiple failed attempts. Please try again later or reset your password if required.`;
    }

    let errorMessage = "Invalid username or password.";

    if (loginResponse.maxAttempts != null) {
      // All registered users will have maxAttempts.
      errorMessage = `${errorMessage} You have ${loginResponse.maxAttempts - (loginResponse.failedAttempts ?? 0)} more attempts remaining before your account is locked.`;
    }

    return errorMessage;
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private resetForm() {
    this.errors = [];
    this.submitted = false;
  }

  // convenience getter for easy access to form fields
  get f() {
    return this.loginForm?.controls;
  }

  onSubmit() {
    this.resetForm();
    this.submitted = true;

    // stop here if form is invalid
    if (this.loginForm?.invalid) {
      this.loginForm.markAllAsTouched();
      return;
    }

    this.loading = true;
    this.authenticationService.login(
      this.f?.username.value,
      this.f?.password.value,
    );
  }

  hasError(prop: AbstractControl) {
    return prop.invalid && (prop.dirty || prop.touched);
  }

  getErrorString(prop: AbstractControl) {
    if (prop.errors?.required) {
      return "This field is required.";
    }
  }

  getError(controlName: string) {
    const prop = this.loginForm?.get(controlName);
    if (prop && this.hasError(prop)) {
      return this.getErrorString(prop);
    }
  }

  onEmailBlur() {
    this.router
      .navigate(["./"], { skipLocationChange: true })
      .catch(console.log);
  }
}

<app-page>
  <ng-container ngProjectAs="content">
    <app-browser-title
      title="Sign in"
      [renderTitle]="false"
    ></app-browser-title>
    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds-from-desktop">
          <gds-error-summary [errors]="errors"></gds-error-summary>
        </div>
      </div>
      <gds-fieldset legend="Sign in">
        <div class="login govuk-grid-row">
          <div class="govuk-grid-column-two-thirds-from-desktop">
            <gds-text-input
              inputId="login-username"
              formControlName="username"
              label="Email"
              width="20"
              [error]="getError('username')"
              [required]="true"
              (blurred)="onEmailBlur()"
              autocomplete="username"
            >
            </gds-text-input>
            <gds-password-input
              inputId="login-password"
              formControlName="password"
              type="password"
              label="Password"
              width="20"
              [error]="getError('password')"
              [required]="true"
              autocomplete="current-password"
            ></gds-password-input>
            <div [style.max-width]="'41ex'">
              <gds-button text="Sign in" type="submit"></gds-button>
            </div>
          </div>
          <div class="govuk-grid-column-one-third-from-desktop govuk-body">
            <h2 class="govuk-heading-m">Forgot your password?</h2>
            <a
              class="govuk-link"
              href="https://publish.bus-data.dft.gov.uk/account/password/reset/"
              >Reset your password</a
            >
          </div>
        </div>
      </gds-fieldset>
    </form>
  </ng-container>
</app-page>

// frontend-two/pages/login.tsx
import { FormEvent, useState, useEffect } from "react";
import { useRouter } from "next/router";
import { BaseLayout } from "@/components/layout/BaseLayout";
import { ErrorSummary } from "@/components/form/ErrorSummary";
import { TextInput } from "@/components/form/TextInput";
import { PasswordInput } from "@/components/form/PasswordInput";
import { loginSchema, LoginSchema } from "@/schemas/login.schema";
import { ErrorInfo } from "@/types";
import { useAuth } from "@/hooks/useAuth";
import { useConfig } from "@/contexts/ConfigContext";
import { LoginResult } from "@/services/auth.service";

const getLoginErrorMessage = (result: LoginResult): string => {
  if (result.locked && result.unlockAt) {
    const diffMs = new Date(result.unlockAt).getTime() - Date.now();
    const diffMins = Math.max(Math.ceil(diffMs / 60000), 0);
    return `Your account is locked for ${diffMins} minutes due to multiple failed attempts. Please try again later or reset your password if required.`;
  }

  let errorMessage = "Invalid username or password.";
  if (result.maxAttempts != null) {
    const remaining = result.maxAttempts - (result.failedAttempts ?? 0);
    errorMessage = `${errorMessage} You have ${remaining} more attempts remaining before your account is locked.`;
  }
  return errorMessage;
};

const LoginPage = () => {
  const router = useRouter();
  const { login } = useAuth();
  const { config } = useConfig();
  const [formData, setFormData] = useState<Partial<LoginSchema>>({
    username: "",
    password: "",
  });
  const [errors, setErrors] = useState<ErrorInfo[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [returnUrl, setReturnUrl] = useState("/dashboard");

  // Capture returnUrl once router query params are available.
  // Only accept relative paths to prevent open redirect attacks.
  useEffect(() => {
    const raw = router.query.returnUrl;
    if (
      typeof raw === "string" &&
      raw.startsWith("/") &&
      !raw.startsWith("//")
    ) {
      setReturnUrl(raw);
    }
  }, [router.query.returnUrl]);

  // Clear errors when form data changes
  useEffect(() => {
    setErrors([]);
  }, [formData]);

  const updateField = (value: string, field: keyof LoginSchema) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    setErrors([]);

    const result = loginSchema.safeParse(formData);
    if (!result.success) {
      setErrors(
        result.error.issues.map((issue) => ({
          id: issue.path.join("."),
          errorMessage: issue.message,
        })),
      );
      return;
    }

    try {
      setIsSubmitting(true);
      const loginResult = await login(
        result.data.username,
        result.data.password,
      );
      if (!loginResult.success) {
        setErrors([
          {
            id: "username",
            errorMessage: getLoginErrorMessage(loginResult),
          },
        ]);
        return;
      }
      if (!loginResult.expiresAt) {
        setErrors([
          {
            id: "username",
            errorMessage: "Login failed",
          },
        ]);
        return;
      }
      router.replace(returnUrl);
    } catch (error) {
      setErrors([
        {
          id: "username",
          errorMessage:
            error instanceof Error
              ? error.message
              : "Invalid username or password.",
        },
      ]);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <BaseLayout title="Sign in - Analyse Bus Open Data" errors={errors}>
      <div className="govuk-grid-row">
        <div className="govuk-grid-column-two-thirds-from-desktop">
          <ErrorSummary errors={errors} />
        </div>
      </div>

      <fieldset className="govuk-fieldset">
        <legend className="govuk-fieldset__legend govuk-fieldset__legend--xl">
          <h1 className="govuk-fieldset__heading">Sign in</h1>
        </legend>

        <form onSubmit={handleSubmit} noValidate>
          <div className="login govuk-grid-row">
            <div className="govuk-grid-column-two-thirds-from-desktop">
              <TextInput<LoginSchema>
                display="Email"
                inputName="username"
                widthClass="govuk-input--width-20"
                value={formData.username}
                initialErrors={errors}
                stateUpdater={updateField}
                maxLength={100}
                required
                autocomplete="username"
              />

              <PasswordInput<LoginSchema>
                display="Password"
                inputName="password"
                widthClass="width20"
                value={formData.password}
                initialErrors={errors}
                stateUpdater={updateField}
                maxLength={100}
                required
                autocomplete="current-password"
              />

              <div style={{ maxWidth: "41ex" }}>
                <button
                  className="govuk-button"
                  data-module="govuk-button"
                  type="submit"
                  disabled={isSubmitting}
                >
                  {isSubmitting ? "Signing in..." : "Sign in"}
                </button>
              </div>
            </div>

            <div className="govuk-grid-column-one-third-from-desktop govuk-body">
              <h2 className="govuk-heading-m">Forgot your password?</h2>
              <a
                className="govuk-link"
                href={`${config?.bodsBaseUrl}/account/password/reset/`}
              >
                Reset your password
              </a>
            </div>
          </div>
        </form>
      </fieldset>
    </BaseLayout>
  );
};

export default LoginPage;
