// frontend/src/app/corridors/create/corridor-stop-list/corridor-stop-list.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { Feature, FeatureCollection, Point } from "geojson";
import { CorridorStop } from "../../types";

@Component({
  selector: "app-corridor-stop-list",
  templateUrl: "./corridor-stop-list.component.html",
  styleUrls: ["./corridor-stop-list.component.scss"],
})
export class CorridorStopListComponent {
  @Input() corridorStops?: FeatureCollection<Point, CorridorStop>;
  @Input() loading = false;
  @Input() isEdit = false;
  @Output() mouseOver = new EventEmitter<Feature<Point, CorridorStop>>();
  @Output() mouseLeave = new EventEmitter<Feature<Point, CorridorStop>>();
  @Output() removeLastStop = new EventEmitter<Feature<Point, CorridorStop>>();
}

<div
  class="corridor-stop-list__stop corridor-stop-list__stop--added"
  [ngClass]="{ 'corridor-stop-list__stop--connected': !isLast }"
  *ngFor="let stop of corridorStops?.features; let isLast = last; let i = index"
  (mouseover)="mouseOver.emit(stop)"
  (mouseleave)="mouseLeave.emit(stop)"
>
  <div class="corridor-stop-list__stop-details">
    <div class="corridor-stop-list__stop-label">
      {{ stop.properties.stopName }}
    </div>
    <div class="corridor-stop-list__naptan">{{ stop.properties.naptan }}</div>
  </div>
  <div *ngIf="isLast && !loading && (isEdit ? i > 0 : true)">
    <button
      type="button"
      class="corridor-stop-list__remove button-link"
      (click)="removeLastStop.emit(stop)"
    >
      Remove
    </button>
  </div>
</div>

// frontend-two/components/corridors/create/CorridorStopList.tsx
import { CorridorStop } from "@/types/corridors";

interface Props {
  corridorStops: CorridorStop[];
  loading: boolean;
  isEdit: boolean;
  onRemoveLastStop: () => void;
}

export const CorridorStopList = ({
  corridorStops,
  loading,
  isEdit,
  onRemoveLastStop,
}: Props) => {
  if (!corridorStops.length) return null;

  return (
    <div className="corridor-stop-list">
      {corridorStops.map((stop, index) => {
        const isLast = index === corridorStops.length - 1;
        const canRemove = isLast && !loading && (isEdit ? index > 0 : true);

        return (
          <div
            key={`${stop.stopId}-${index}`}
            className={`corridor-stop-list__stop corridor-stop-list__stop--added${
              isLast ? "" : " corridor-stop-list__stop--connected"
            }`}
          >
            <div className="corridor-stop-list__stop-details">
              <div className="corridor-stop-list__stop-label">
                {stop.stopName}
              </div>
              <div className="corridor-stop-list__naptan">{stop.naptan}</div>
            </div>
            {canRemove ? (
              <button
                type="button"
                className="govuk-link button-link"
                onClick={onRemoveLastStop}
              >
                Remove
              </button>
            ) : null}
            {!isLast ? (
              <hr className="govuk-section-break govuk-section-break--visible" />
            ) : null}
          </div>
        );
      })}
    </div>
  );
};
