// frontend/src/app/corridors/delete-corridor-modal/delete-corridor-modal.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { Corridor } from "../types";

@Component({
  selector: "app-delete-corridor-modal",
  templateUrl: "./delete-corridor-modal.component.html",
})
export class DeleteCorridorModalComponent {
  @Input() corridor?: Corridor;
  @Output() deleteCorridor = new EventEmitter<Corridor>();
}

<app-modal
  #deleteModal
  modalTitle="Delete corridor?"
  identifier="deleteCorridor"
>
  <p class="govuk-body" id="delete-modal-body">
    Are you sure you want to delete the corridor
    <strong>{{ corridor?.name }}</strong
    >? This operation cannot be undone.
  </p>
  <div class="flex-row justify-content-between">
    <gds-button
      text="Cancel"
      spaceBelow="0"
      appearance="secondary"
      (click)="deleteModal.close()"
    ></gds-button>
    <gds-button
      text="Delete corridor"
      spaceBelow="0"
      (click)="deleteCorridor.emit(corridor)"
      appearance="warning"
    ></gds-button>
  </div>
</app-modal>

// frontend-two/components/corridors/create/DeleteCorridorModal.tsx
interface Props {
  open: boolean;
  corridorName: string;
  isDeleting: boolean;
  onCancel: () => void;
  onDelete: () => void;
}

export const DeleteCorridorModal = ({
  open,
  corridorName,
  isDeleting,
  onCancel,
  onDelete,
}: Props) => {
  if (!open) return null;

  return (
    <div className="govuk-inset-text" role="alert" aria-live="polite">
      <h2 className="govuk-heading-m govuk-!-margin-bottom-2">
        Delete corridor?
      </h2>
      <p className="govuk-body">
        Are you sure you want to delete the corridor{" "}
        <strong>{corridorName}</strong>? This operation cannot be undone.
      </p>
      <div className="govuk-button-group">
        <button
          type="button"
          className="govuk-button govuk-button--secondary"
          data-module="govuk-button"
          onClick={onCancel}
          disabled={isDeleting}
        >
          Cancel
        </button>
        <button
          type="button"
          className="govuk-button govuk-button--warning"
          data-module="govuk-button"
          onClick={onDelete}
          disabled={isDeleting}
        >
          Delete corridor
        </button>
      </div>
    </div>
  );
};
