// frontend/src/app/corridors/create/stop-search-list/stop-search-list.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { Feature, FeatureCollection, Point } from "geojson";
import { isNotNullOrUndefined } from "../../../shared/rxjs-operators";
import { CorridorStop } from "../../types";

export const LIST_LEN = 100;

@Component({
  selector: "app-stop-search-list",
  templateUrl: "./stop-search-list.component.html",
  styleUrls: [
    "../corridor-stop-list/corridor-stop-list.component.scss",
    "./stop-search-list.component.scss",
  ],
})
export class StopSearchListComponent {
  @Input() matchingStops?: FeatureCollection<Point, CorridorStop>;
  @Input() isFirstStop = true;
  @Output() mouseOver: EventEmitter<Feature<Point, CorridorStop>> =
    new EventEmitter<Feature<Point, CorridorStop>>();
  @Output() mouseLeave: EventEmitter<Feature<Point, CorridorStop>> =
    new EventEmitter<Feature<Point, CorridorStop>>();
  @Output() addStop: EventEmitter<Feature<Point, CorridorStop>> =
    new EventEmitter<Feature<Point, CorridorStop>>();

  listSize = LIST_LEN;

  get stops(): Feature<Point, CorridorStop>[] | undefined {
    return this.matchingStops?.features.slice(0, this.listSize);
  }

  get showMoreBtn(): boolean {
    return (
      isNotNullOrUndefined(this.stops) &&
      (this.matchingStops?.features?.length ?? 0) > this.listSize
    );
  }

  showMore() {
    this.listSize += LIST_LEN;
  }
}

<div
  class="corridor-stop-list__stop corridor-stop-list__stop--matching"
  *ngFor="let stop of stops"
  (mouseover)="mouseOver.emit(stop)"
  (mouseleave)="mouseLeave.emit(stop)"
>
  <div
    class="corridor-stop-list__stop-details corridor-stop-list__stop-details--no-graphic"
  >
    <div class="corridor-stop-list__stop-label">
      {{ stop.properties.stopName }}
    </div>
    <div class="corridor-stop-list__naptan">
      {{ stop.properties.localityName }} {{ stop.properties.naptan }}
    </div>
  </div>
  <div>
    <gds-button
      [text]="!isFirstStop ? 'Add' : 'Select'"
      appearance="secondary"
      spaceBelow="0"
      (click)="addStop.emit(stop)"
    ></gds-button>
  </div>
</div>
<gds-button
  *ngIf="showMoreBtn"
  text="Show more"
  appearance="secondary"
  spaceAbove="4"
  spaceBelow="2"
  (click)="showMore()"
></gds-button>

// frontend-two/components/corridors/create/StopSearchList.tsx
import { clsx } from "clsx";
import styles from "./corridor-stop-list.module.scss";
import { useMemo, useState } from "react";
import { CorridorStop } from "@/types/corridors";

const LIST_LEN = 100;

interface Props {
  matchingStops: CorridorStop[];
  isFirstStop: boolean;
  onAddStop: (stop: CorridorStop) => void;
  showGraphic?: boolean;
}

export const StopSearchList = ({
  matchingStops,
  isFirstStop,
  onAddStop,
  showGraphic = false,
}: Props) => {
  const [listSize, setListSize] = useState(LIST_LEN);

  const stops = useMemo(
    () => matchingStops.slice(0, listSize),
    [matchingStops, listSize],
  );

  const showMoreBtn = matchingStops.length > listSize;

  return (
    <>
      {stops.map((stop, index) => (
        <div
          key={`${stop.stopId}-${index}`}
          className={clsx(
            styles["corridor-stop-list__stop"],
            styles["corridor-stop-list__stop--matching"],
          )}
        >
          <div
            className={
              showGraphic
                ? styles["corridor-stop-list__stop-details"]
                : styles["corridor-stop-list__stop-details--no-graphic"]
            }
          >
            <div className={styles["corridor-stop-list__stop-label"]}>
              {stop.stopName}
            </div>
            <div className={styles["corridor-stop-list__naptan"]}>
              {stop.localityName ? `${stop.localityName} ` : ""}
              {stop.naptan}
            </div>
          </div>
          <button
            type="button"
            className="govuk-button govuk-button--secondary govuk-!-margin-bottom-0"
            data-module="govuk-button"
            onClick={() => onAddStop(stop)}
          >
            {isFirstStop ? "Select" : "Add"}
          </button>
        </div>
      ))}

      {showMoreBtn ? (
        <button
          type="button"
          className="govuk-button govuk-button--secondary govuk-!-margin-top-4"
          data-module="govuk-button"
          onClick={() => setListSize((current) => current + LIST_LEN)}
        >
          Show more
        </button>
      ) : null}
    </>
  );
};
